// Generated barrel for the 86 capability prompt functions (M15-3).
// One import site for the registry; the grouping of the files themselves is
// only a file-length concern and carries no meaning.

import type { CapabilityPrompt } from "../types";
import { notes, doubt, career, assignment, crunch, tutor, syllabus, formula, formula_decoder, admissions, flashcards, essay_grade, personal_statement, interview_questions, interview_eval, mindmap, presentation, debate, exam_sim, vocab, research, coach_briefing } from "./group-01";
import { coach_chat, mark_scheme, mark_scheme_eval, subject_picker, essay_blueprint, concept_web, paper_dissector, lang_analyzer, lab_report, uni_match, compare, source, practice, predict, memory_palace, analogy, case_study, timeline, reading, grammar, study_guide, exam_strategy, concept_connect, model_answer, papers_explain, redemption_set } from "./group-02";
import { argument, cremator, formula_recall, exam_debrief, circuit_breaker, topic_half_life, analysis_hub, application_plan, brain_budget, exam_triage, focus_lab, language_lab, memory_toolkit, recall_studio, reference_builder, report_writer } from "./group-03";
import { research_suite, revision_intel, study_command, uni_prep, writing_tools, paper_triage, doubt_cross_question, doubt_cross_eval, calibration_questions, feynman_probe, feynman_eval, paper_pattern, last_night_triage, paper_autopsy, silent_topic_audit } from "./group-04";
import { examiner_mind, last_night_brief, marks_autopsy, panic_triage, marks_forensics, paper_trauma_map, marks_obituary } from "./group-05";

export const PROMPTS: Readonly<Record<string, CapabilityPrompt>> = Object.freeze({
  notes,
  doubt,
  career,
  assignment,
  crunch,
  tutor,
  syllabus,
  formula,
  formula_decoder,
  admissions,
  flashcards,
  essay_grade,
  personal_statement,
  interview_questions,
  interview_eval,
  mindmap,
  presentation,
  debate,
  exam_sim,
  vocab,
  research,
  coach_briefing,
  coach_chat,
  mark_scheme,
  mark_scheme_eval,
  subject_picker,
  essay_blueprint,
  concept_web,
  paper_dissector,
  lang_analyzer,
  lab_report,
  uni_match,
  compare,
  source,
  practice,
  predict,
  memory_palace,
  analogy,
  case_study,
  timeline,
  reading,
  grammar,
  study_guide,
  exam_strategy,
  concept_connect,
  model_answer,
  papers_explain,
  redemption_set,
  argument,
  cremator,
  formula_recall,
  exam_debrief,
  circuit_breaker,
  topic_half_life,
  analysis_hub,
  application_plan,
  brain_budget,
  exam_triage,
  focus_lab,
  language_lab,
  memory_toolkit,
  recall_studio,
  reference_builder,
  report_writer,
  research_suite,
  revision_intel,
  study_command,
  uni_prep,
  writing_tools,
  paper_triage,
  doubt_cross_question,
  doubt_cross_eval,
  calibration_questions,
  feynman_probe,
  feynman_eval,
  paper_pattern,
  last_night_triage,
  paper_autopsy,
  silent_topic_audit,
  examiner_mind,
  last_night_brief,
  marks_autopsy,
  panic_triage,
  marks_forensics,
  paper_trauma_map,
  marks_obituary,
});
