#!/usr/bin/env python3
"""
Ledger Error Sync
Runs hourly — pulls new errors from Supabase, writes to LedgerBrain/Bugs/
"""

import os, sys, json, re
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests
except ImportError:
    print("requests not installed. Run: pip install requests")
    sys.exit(1)

# ── Paths ─────────────────────────────────────────────────────────────────────
VAULT    = Path(r"C:\Users\DELL\Documents\LedgerBrain")
BUGS_DIR = VAULT / "Bugs"
ENV_FILE = Path(r"C:\Users\DELL\Downloads\design_handoff_ledger\ledger\.env.local")
STATE    = BUGS_DIR / ".last-sync"

TYPE_LABEL = {
    "js_error":            "JS Error",
    "unhandled_rejection": "Promise Rejection",
    "blank_screen":        "Blank Screen",
    "react_crash":         "React Crash",
}

TYPE_ICON = {
    "js_error":            "[JS]",
    "unhandled_rejection": "[PROMISE]",
    "blank_screen":        "[BLANK]",
    "react_crash":         "[REACT]",
}


def read_env() -> dict:
    if not ENV_FILE.exists():
        return {}
    env = {}
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def last_sync_time() -> str:
    if STATE.exists():
        return STATE.read_text(encoding="utf-8").strip()
    # default: 24h ago
    from datetime import timedelta
    t = datetime.now(timezone.utc) - timedelta(hours=24)
    return t.strftime("%Y-%m-%dT%H:%M:%S+00:00")


def fetch_errors(url: str, key: str, since: str) -> list:
    endpoint = f"{url}/rest/v1/error_logs"
    params = {
        "select": "*",
        "created_at": f"gte.{since}",
        "order": "created_at.asc",
    }
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
    }
    r = requests.get(endpoint, params=params, headers=headers, timeout=15)
    r.raise_for_status()
    return r.json()


def fmt_error(e: dict) -> str:
    ts  = e.get("created_at", "")[:19].replace("T", " ")
    typ = e.get("type", "unknown")
    label = TYPE_LABEL.get(typ, typ.upper())
    icon  = TYPE_ICON.get(typ, "[?]")
    url   = e.get("url") or ""
    route = e.get("route") or url
    msg   = e.get("message") or "(no message)"
    stack = e.get("stack") or ""
    ctx   = e.get("context") or {}

    lines = [
        f"### {icon} {label} · {ts}",
        f"",
        f"**Route:** `{route}`",
        f"**Message:** {msg}",
    ]

    if ctx:
        ctx_str = json.dumps(ctx, ensure_ascii=False)
        if len(ctx_str) < 300:
            lines.append(f"**Context:** `{ctx_str}`")

    if stack:
        short = "\n".join(stack.splitlines()[:8])
        lines += ["", "```", short, "```"]

    lines.append("")
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def write_day(errors: list, date_str: str) -> Path:
    BUGS_DIR.mkdir(parents=True, exist_ok=True)
    path = BUGS_DIR / f"{date_str}.md"

    new_content = "\n".join(fmt_error(e) for e in errors)

    if path.exists():
        existing = path.read_text(encoding="utf-8")
        # append after the existing content
        combined = existing.rstrip() + "\n\n" + new_content
    else:
        combined = f"""---
date: {date_str}
count: {len(errors)}
---

# Bug Log · {date_str}

> Auto-generated by Ledger Error Sync. Source: Supabase error_logs table.

---

{new_content}"""

    path.write_text(combined, encoding="utf-8")
    return path


def update_index(by_day: dict) -> None:
    index = BUGS_DIR / "00-Bugs-Index.md"
    BUGS_DIR.mkdir(parents=True, exist_ok=True)

    lines = []
    for date_str in sorted(by_day.keys(), reverse=True):
        count  = len(by_day[date_str])
        types  = {}
        for e in by_day[date_str]:
            t = e.get("type", "unknown")
            types[t] = types.get(t, 0) + 1
        type_summary = ", ".join(f"{v}x {TYPE_LABEL.get(k,k)}" for k, v in types.items())
        lines.append(f"- [[{date_str}]] — {count} error{'s' if count != 1 else ''} · {type_summary}")

    block = "\n".join(lines)

    if index.exists():
        text = index.read_text(encoding="utf-8")
        # replace everything after the --- separator
        if "---\n" in text:
            head = text.split("---\n")[0] + "---\n"
            index.write_text(head + "\n" + block + "\n", encoding="utf-8")
        else:
            index.write_text(text + "\n" + block + "\n", encoding="utf-8")
    else:
        index.write_text(f"""# Bug Log Index

All error days, most recent first. Auto-updated by error-sync.py.

---

{block}
""", encoding="utf-8")


def main():
    env  = read_env()
    url  = env.get("NEXT_PUBLIC_SUPABASE_URL", "").strip()
    key  = env.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()

    if not url or not key or "placeholder" in url:
        print("ERROR: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not found in .env.local")
        sys.exit(1)

    since = last_sync_time()
    now   = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")

    print(f"Ledger Error Sync -> fetching errors since {since}")
    errors = fetch_errors(url, key, since)
    print(f"Found {len(errors)} new error(s)")

    if not errors:
        BUGS_DIR.mkdir(parents=True, exist_ok=True)
        STATE.write_text(now, encoding="utf-8")
        print("Nothing to write. Done.")
        return

    # Group by date
    by_day: dict[str, list] = {}
    for e in errors:
        date_str = e.get("created_at", "")[:10]
        if not date_str:
            continue
        by_day.setdefault(date_str, []).append(e)

    written = []
    for date_str, day_errors in by_day.items():
        path = write_day(day_errors, date_str)
        written.append(f"  {date_str}: {len(day_errors)} error(s) -> {path.name}")

    update_index(by_day)
    STATE.write_text(now, encoding="utf-8")

    print("Written:")
    for w in written:
        print(w)
    print("Done. Open LedgerBrain/Bugs/ in Obsidian.")


if __name__ == "__main__":
    main()
