// ═══════════════════════════════════════════════════════════════════════════
// Rebuild supabase/pending/*.sql from supabase/migrations/*.sql
//
// The parts were concatenated by hand the first time, which meant that fixing
// a migration silently left the pasteable copy stale - exactly what happened
// after 012 was corrected for the text[] drift. A generator makes the parts a
// derived artifact: fix the migration, re-run this, and the paste agrees.
//
//   node scripts/build-pending.mjs
//   node scripts/build-pending.mjs --check    (CI: fail if parts are stale)
//
// Grouping is fixed rather than size-balanced so that part numbers stay
// stable across runs - a moving boundary would be miserable for someone
// halfway through pasting.
// ═══════════════════════════════════════════════════════════════════════════

import fs from "node:fs";
import path from "node:path";

const MIG = "supabase/migrations";
const OUT = "supabase/pending";

/** Production is evidenced at 000-007; these are what it lacks. */
const PARTS = [
  ["008", "009", "010", "011", "012", "013"],
  ["014", "015", "016"],
  ["017", "018", "019", "020", "021", "022"],
  ["023", "024", "025"],
  ["026", "027", "028", "029", "030"],
  ["031", "032", "033", "034", "035"],
  // 036 fixes a defect in 029. 029 is already applied and checksum-locked, so
  // 009 refuses an edit to it; the fix ships as its own part.
  ["036"],
];

const files = fs.readdirSync(MIG).filter((f) => f.endsWith(".sql"));
const byVersion = new Map();
for (const f of files) {
  const m = f.match(/^(\d{3})_/);
  if (m) byVersion.set(m[1], f);
}

const header = (n, total, versions) => `-- ${"═".repeat(75)}
-- STUDYLEDGER — PENDING MIGRATIONS, PART ${n} OF ${total}
--
-- ${versions.join(", ")}
--
-- RUN THE PARTS IN ORDER. Each part is a whole number of migrations and is
-- idempotent, so a part that is interrupted can simply be run again.
--
-- Supabase → SQL Editor → New query. Press Ctrl+A then Delete FIRST: the
-- editor runs only the highlighted text if anything is selected, and a
-- partial run reports success.
--
-- GENERATED by scripts/build-pending.mjs. Do not edit by hand: fix the
-- migration in supabase/migrations and regenerate, or the paste and the
-- repo will disagree.
-- ${"═".repeat(75)}
`;

const FOOTER = `
-- What this part left behind, from the database rather than from a claim:
SELECT version, name, recorded_by FROM supabase_migrations.schema_migrations ORDER BY version;
`;

const check = process.argv.includes("--check");
let stale = 0;

PARTS.forEach((versions, i) => {
  const n = i + 1;
  let body = header(n, PARTS.length, versions);
  for (const v of versions) {
    const f = byVersion.get(v);
    if (!f) throw new Error(`no migration file for version ${v}`);
    body += `\n-- ─── ${f} ───\n\n`;
    body += fs.readFileSync(path.join(MIG, f), "utf8").replace(/\r\n/g, "\n").trimEnd();
    body += "\n";
  }
  body += FOOTER;

  const out = path.join(OUT, `part-0${n}.sql`);
  const prev = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : null;
  if (prev === body) {
    console.log(`  unchanged  part-0${n}.sql`);
    return;
  }
  if (check) {
    stale++;
    console.log(`  STALE      part-0${n}.sql (contains ${versions.join(", ")})`);
    return;
  }
  fs.writeFileSync(out, body);
  const kb = Math.round(Buffer.byteLength(body) / 1024);
  console.log(`  ${prev === null ? "created" : "rebuilt"}    part-0${n}.sql  ${versions.join(" ")}  ${kb} KB`);
});

if (check && stale) {
  console.log(`\n${stale} part(s) do not match supabase/migrations. Run: node scripts/build-pending.mjs`);
  process.exit(1);
}
console.log(check ? "\nParts match the migrations." : "\nParts rebuilt from the migrations.");
