-- ═══════════════════════════════════════════════════════════════════════════
-- STUDYLEDGER — PENDING MIGRATIONS, PART 7 OF 8
--
-- 036
--
-- RUN THE PARTS IN ORDER. Each part is a whole number of migrations and is
-- idempotent, so a part that is interrupted can simply be run again.
--
-- Supabase → SQL Editor → New query. Press Ctrl+A then Delete FIRST: the
-- editor runs only the highlighted text if anything is selected, and a
-- partial run reports success.
--
-- GENERATED by scripts/build-pending.mjs. Do not edit by hand: fix the
-- migration in supabase/migrations and regenerate, or the paste and the
-- repo will disagree.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 036_parent_projection_array_fix.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 036_parent_projection_array_fix.sql
--
-- A DEFECT FIX. 029's `get_parent_projection()` cannot log which categories it
-- returned, because seven statements append to a TEXT[] as though it were a
-- string:
--
--   v_cats := v_cats || 'consistency';
--
-- In PL/pgSQL, `text[] || unknown-literal` makes Postgres parse the literal as
-- an ARRAY LITERAL, so the call fails with:
--
--   malformed array literal: "consistency"
--   DETAIL: Array value must start with "{" or dimension information.
--
-- The effect is not cosmetic. The failure happens in the INSERT that writes
-- `parent_access_log`, which is the whole of V.8.7: *"every parent read
-- appends a parent_access_log row the student can read"*. So today, ANY parent
-- read with at least one category enabled raises instead of returning, and the
-- student's record of who looked at what is never written. A parent with a
-- fully-default (all-FALSE) policy is unaffected, which is exactly why this
-- survived: the migration's own verification only exercised the empty case.
--
-- ── WHY A NEW FILE RATHER THAN AN EDIT TO 029 ────────────────────────────
-- 029 is APPLIED to production and recorded in the ledger with a checksum.
-- 009's `record_migration()` refuses a changed checksum for an applied
-- version on purpose: *"the file was edited after it was applied; write a new
-- migration instead"*. That guard is correct and this file is what it asks
-- for. 029 is left exactly as it ran.
--
-- ── THE FIX ──────────────────────────────────────────────────────────────
-- `array_append(v_cats, 'consistency')` states the intent unambiguously and
-- cannot be re-read as an array literal. The rest of the function is
-- reproduced verbatim from 029, because CREATE OR REPLACE FUNCTION replaces
-- the whole body and a partial copy would silently drop behaviour.
--
-- Everything else about the function is unchanged: same signature, same
-- SECURITY DEFINER, same search_path, same grants, same revocation checks,
-- same category gating, same output shape.
--
-- Idempotent. Safe to re-run.
-- Run in: Supabase → SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.get_parent_projection(
  p_student_id UUID
) RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_parent UUID := auth.uid();
  v_conn   public.parent_connections;
  v_policy public.parent_share_policies;
  v_out    JSONB := '{}'::jsonb;
  v_cats   TEXT[] := '{}';
BEGIN
  IF v_parent IS NULL THEN
    RAISE EXCEPTION 'get_parent_projection: no authenticated caller' USING ERRCODE = '28000';
  END IF;

  SELECT * INTO v_conn FROM public.parent_connections
   WHERE student_id = p_student_id AND parent_id = v_parent AND state = 'active';

  IF v_conn IS NULL THEN
    -- Deliberately one message for "never connected" and "revoked" — a
    -- distinguishing error would let a caller probe for which is true.
    RAISE EXCEPTION 'no active parent connection to this student' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_policy FROM public.parent_share_policies
   WHERE student_id = p_student_id AND is_current;

  -- No policy row is the same as every category FALSE. System-tier fields
  -- still populate below.
  v_out := jsonb_build_object(
    'system', jsonb_build_object(
      'connectionActive', TRUE,
      'connectionSince', v_conn.created_at,
      'policyVersion', COALESCE(v_policy.version, 0),
      'policyUpdatedAt', v_policy.effective_from
    )
  );

  IF COALESCE(v_policy.score_trajectory, FALSE) THEN
    v_out := v_out || jsonb_build_object('scoreTrajectory',
      (SELECT jsonb_agg(to_jsonb(s) - 'student_id' ORDER BY s.captured_on DESC)
         FROM (SELECT * FROM public.parent_score_view WHERE student_id = p_student_id
                ORDER BY captured_on DESC LIMIT 30) s));
    v_cats := array_append(v_cats, 'score_trajectory');
  END IF;

  IF COALESCE(v_policy.dimension_breakdown, FALSE) THEN
    v_out := v_out || jsonb_build_object('dimensionBreakdown',
      (SELECT to_jsonb(s) - 'student_id' FROM public.parent_score_view s
        WHERE student_id = p_student_id ORDER BY captured_on DESC LIMIT 1));
    v_cats := array_append(v_cats, 'dimension_breakdown');
  END IF;

  IF COALESCE(v_policy.subject_state, FALSE) THEN
    v_out := v_out || jsonb_build_object('subjectState',
      (SELECT jsonb_agg(to_jsonb(s) - 'student_id')
         FROM public.parent_subject_view s WHERE student_id = p_student_id));
    v_cats := array_append(v_cats, 'subject_state');
  END IF;

  IF COALESCE(v_policy.progress_fixing, FALSE) THEN
    v_out := v_out || jsonb_build_object('progressFixing',
      (SELECT to_jsonb(s) - 'student_id' FROM public.parent_progress_view s
        WHERE student_id = p_student_id));
    v_cats := array_append(v_cats, 'progress_fixing');
  END IF;

  IF COALESCE(v_policy.consistency, FALSE) THEN
    v_out := v_out || jsonb_build_object('consistency',
      (SELECT to_jsonb(s) - 'student_id' FROM public.parent_consistency_view s
        WHERE student_id = p_student_id));
    v_cats := array_append(v_cats, 'consistency');
  END IF;

  IF COALESCE(v_policy.upcoming_exams, FALSE) AND to_regclass('public.parent_exams_view') IS NOT NULL THEN
    v_out := v_out || jsonb_build_object('upcomingExams',
      (SELECT exams FROM public.parent_exams_view WHERE student_id = p_student_id));
    v_cats := array_append(v_cats, 'upcoming_exams');
  END IF;

  IF COALESCE(v_policy.assessment_activity, FALSE) THEN
    v_out := v_out || jsonb_build_object('assessmentActivity',
      (SELECT to_jsonb(s) - 'student_id' FROM public.parent_assessment_view s
        WHERE student_id = p_student_id));
    v_cats := array_append(v_cats, 'assessment_activity');
  END IF;

  INSERT INTO public.parent_access_log (student_id, parent_id, connection_id, policy_version, categories_read)
  VALUES (p_student_id, v_parent, v_conn.connection_id, COALESCE(v_policy.version, 0), v_cats);

  RETURN v_out;
END;
$$;

REVOKE ALL ON FUNCTION public.get_parent_projection(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_parent_projection(UUID) TO authenticated, service_role;

COMMENT ON FUNCTION public.get_parent_projection(UUID) IS
  'The only parent read path (architecture N.5). Every key it can emit traces to one of the five Shared views in 029 section 5; there is no branch that can select a Private column, because none is named anywhere in this function body. Logs every call to parent_access_log (V.8.7). Body identical to 029 except that category names are appended with array_append() — see 036.';


-- ── Verification the founder can run after applying this file ──────────────
--
-- Proves the defect is gone WITHOUT needing a signed-in parent: the old body
-- failed while building the array, so a direct array_append round-trip on the
-- same literals is the thing that used to break.
DO $$
DECLARE
  v_cats TEXT[] := '{}';
BEGIN
  v_cats := array_append(v_cats, 'consistency');
  v_cats := array_append(v_cats, 'upcoming_exams');
  IF array_length(v_cats, 1) <> 2 THEN
    RAISE EXCEPTION '036: array_append did not build the category list';
  END IF;
  RAISE NOTICE '036: category list builds correctly: %', v_cats;
END $$;

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '036',
  '036_parent_projection_array_fix.sql',
  '6b3145d9a2c3ce7c3ffe809192fae3e82eff4325ae6cdfb888ae9b850b08d05f',
  'self'
);

-- What this part left behind, from the database rather than from a claim:
SELECT version, name, recorded_by FROM supabase_migrations.schema_migrations ORDER BY version;
