-- ═══════════════════════════════════════════════════════════════════════════
-- STUDYLEDGER — PENDING MIGRATIONS, PART 6 OF 8
--
-- 031, 032, 033, 034, 035
--
-- RUN THE PARTS IN ORDER. Each part is a whole number of migrations and is
-- idempotent, so a part that is interrupted can simply be run again.
--
-- Supabase → SQL Editor → New query. Press Ctrl+A then Delete FIRST: the
-- editor runs only the highlighted text if anything is selected, and a
-- partial run reports success.
--
-- GENERATED by scripts/build-pending.mjs. Do not edit by hand: fix the
-- migration in supabase/migrations and regenerate, or the paste and the
-- repo will disagree.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 031_personal_model.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 031_personal_model.sql   ·   M19
--
-- EXECUTION_PLAN M19:
--   M19-1  Typed, bounded dimensions; signal extraction; aggregation.
--          Done when: I.2 — "the list is bounded, not open."
--   M19-2  The two-column explicit-over-inferred override, enforced by
--          COLUMN-LEVEL GRANT. Done when: V.5.2–V.5.4 — the aggregator is
--          refused by the DATABASE, not by policy.
--   M19-3  Confidence, decay, floor, disclosure of fallback.
--          Done when: V.5.6, V.5.7 — the fallback is stated, never silent.
--   M19-4  `explicit_value` restored exactly by L1 replay. Done when: V.5.5.
--
-- Architecture Part I in full; C.3 `PersonalModel` / `PersonalModelSignal`;
-- H.1 (L1/L2 layering); I.6's four independent mechanisms.
--
-- NOT APPLIED to any database. Same posture as every migration since 015.
--
--
-- WHAT THIS FILE ADDS, AND WHY IT IS ONE FILE
--
--   1 · personal_model_dimension    I.2's bounded set, AS A TYPE — an enum,
--                                    not a TEXT + CHECK, because a client that
--                                    somehow reaches this column with a raw
--                                    INSERT should get a type error from
--                                    Postgres itself, not a constraint
--                                    violation a future migration could widen
--                                    by accident.
--   2 · personal_model_signals      C.3 `PersonalModelSignal` — L1, append-
--                                    only raw evidence. What the extractors in
--                                    `lib/personal-model.ts` write.
--   3 · personal_model              C.3 `PersonalModel` — L2, one row per
--                                    (student, dimension). `explicit_value`
--                                    and `inferred_value` are two columns,
--                                    never one (I.6 mechanism 1);
--                                    `effective_value` is GENERATED (I.6
--                                    mechanism 2).
--   4 · THE AGGREGATOR ROLE          A Postgres role strictly narrower than
--                                    `service_role`, used for nothing except
--                                    running the inference aggregator
--                                    (`lib/personal-model-aggregator.ts`).
--                                    §5 gives it write access to
--                                    `inferred_value`, `confidence`,
--                                    `evidence_count`, `last_signal_at` and
--                                    NOTHING else — not `explicit_value`, not
--                                    `overridden_at`. This is M19-2's
--                                    "refused by the database, not by
--                                    policy": RLS does not bind a role
--                                    (`service_role` already proves this —
--                                    016 §"REVOKE service_role" is the
--                                    precedent for restricting a privileged
--                                    role's OWN columns), so the guarantee has
--                                    to be a GRANT, and this is that GRANT.
--
--
-- WHY A NEW ROLE, AND NOT JUST A NARROWER GRANT TO `service_role`
--
-- Every other privileged write in this codebase runs as `service_role`,
-- including the ONE path that is allowed to touch `explicit_value` — the
-- server-side projector that turns a `PREFERENCE_SET` event into a written
-- column (I.6 mechanism 3, "setting is an event"). If the aggregator also
-- ran as `service_role`, restricting `service_role`'s own grant on
-- `explicit_value` would restrict BOTH writers at once — there would be no
-- way to grant the projector what it needs without also granting it to the
-- aggregator. Two writers with different trust levels need two roles. The
-- aggregator is the one that is NEW and NARROW, so it is the one that gets
-- the new role; the projector keeps using `service_role`, unchanged, exactly
-- the way every other L2 rebuild in this codebase already does.
--
-- `personal_model_aggregator` is a Postgres LOGIN role. In production it is
-- reached the same way Supabase's own `anon` / `authenticated` /
-- `service_role` are reached: a JWT whose `role` claim names it, signed with
-- the project's JWT secret, held ONLY by the aggregator job's own runtime
-- credential — never the credential `app/api/**` routes use. That credential
-- is out of scope for a migration file; what this file guarantees is what
-- happens if that JWT is ever used to attempt the one write it must never
-- be able to make.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · THE BOUNDED DIMENSION TYPE (M19-1, I.2)
--
-- Nine names, transcribed from I.2's table in its own order. Adding a tenth
-- is `ALTER TYPE … ADD VALUE` plus a code change in
-- `lib/personal-model.ts:PERSONAL_MODEL_DIMENSIONS` — both are migrations,
-- deliberately, so the model cannot grow opaquely at runtime (I.2: "Adding a
-- dimension is a code change and a migration").
--
-- `ALTER TYPE … ADD VALUE` cannot run inside a transaction block, which is
-- why `academic_events.event_type` (015) uses a CHECK instead — that table's
-- list already grows every milestone. This one does not: I.2 calls it
-- "bounded", and a real ENUM is the stronger statement of exactly that claim,
-- at the cost of a same posture 018's `academic_events_p*` partitions accept
-- elsewhere — a future addition is a slightly heavier migration, in exchange
-- for a type system that refuses an unbounded one today.
-- ═══════════════════════════════════════════════════════════════════════════

DO $$ BEGIN
  CREATE TYPE public.personal_model_dimension AS ENUM (
    'explanation_style',
    'communication_tone',
    'question_format_mix',
    'difficulty_preference',
    'session_length',
    'working_window',
    'correction_method',
    'notification_appetite',
    'recommendation_aggressiveness'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE public.personal_model_dimension IS
  'I.2 — the bounded, typed dimension list. Mirrors PERSONAL_MODEL_DIMENSIONS '
  'in lib/personal-model.ts; tests/personal-model.test.mjs asserts the two '
  'never drift.';


-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · `personal_model_signals` — C.3, L1, RAW EVIDENCE, APPEND-ONLY
--
-- I.4: "A signal must be derivable from an event that already exists for an
-- academic reason." `source_event_id` names that event but carries no FK —
-- `academic_events` is HASH-PARTITIONED on `student_id` (015 §"THE
-- PARTITIONING DECISION"), and a foreign key into a partitioned table must
-- name the full partition key; `input_watermark_event_id` on every other L2
-- table in this codebase (021, 026, 027) already accepts the same trade for
-- the same reason. Existence and student-ownership of `source_event_id` are
-- checked by the extractor's own query, not by this table.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.personal_model_signals (
  signal_id        UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dimension         public.personal_model_dimension NOT NULL,
  observed_value    JSONB       NOT NULL,
  weight            NUMERIC     NOT NULL CHECK (weight >= 0 AND weight <= 1),
  source_event_id   UUID        NOT NULL,
  observed_at       TIMESTAMPTZ NOT NULL,
  extractor_version SMALLINT    NOT NULL CHECK (extractor_version >= 1),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS personal_model_signals_student_dim_idx
  ON public.personal_model_signals (student_id, dimension, observed_at);

-- One extractor run must not double-count the same event for the same
-- dimension — the extractor is deterministic (I.3), so re-running it over a
-- window it already covered should be a no-op, not a re-vote.
CREATE UNIQUE INDEX IF NOT EXISTS personal_model_signals_dedupe_idx
  ON public.personal_model_signals (student_id, dimension, source_event_id);


-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · `personal_model` — C.3, L2, DERIVED STATE, A PROJECTION
--
-- I.6, verbatim: "Two columns, not one... The aggregator has write access to
-- `inferred_value` only... An inference is physically incapable of
-- overwriting a choice." §5 is where that sentence becomes a GRANT.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.personal_model (
  student_id          UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dimension           public.personal_model_dimension NOT NULL,

  -- I.6 mechanism 3/4 — written ONLY by the PREFERENCE_SET projector
  -- (service_role), and ONLY in response to a `PREFERENCE_SET` event. `NULL`
  -- is "no explicit choice", which is different from "cleared" — a clear is
  -- itself a `PREFERENCE_SET{value:null}` event that leaves this column
  -- `NULL` again, not a distinct sentinel, because I.6 mechanism 4 requires
  -- clearing to be exactly as event-sourced as setting.
  explicit_value      JSONB,
  overridden_at        TIMESTAMPTZ,

  -- Written ONLY by the aggregator role (§5).
  inferred_value       JSONB,
  confidence           NUMERIC     CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  evidence_count        INTEGER     NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  last_signal_at        TIMESTAMPTZ,

  -- I.6 mechanism 2 — THE ONLY PLACE `effective_value` IS COMPUTED, ANYWHERE.
  -- `COALESCE(explicit_value, inferred_value)` — no product default here: I.5's
  -- default fallback is a PRODUCT-LAYER constant (`lib/personal-model.ts`'s
  -- `resolveEffectiveValue`), not a database literal, because the default
  -- differs by dimension and a generated column cannot branch on which row
  -- it is. A reader that needs the disclosed-default behaviour calls
  -- `resolveEffectiveValue`; a reader that only needs "explicit-if-set-else-
  -- inferred" reads this column directly and never computes it by hand.
  effective_value      JSONB GENERATED ALWAYS AS (COALESCE(explicit_value, inferred_value)) STORED,

  -- C.3's watermark — same purpose as 026 §4's `input_watermark_event_id`:
  -- makes a stale aggregation detectable rather than silently wrong.
  input_watermark_event_id UUID,
  input_watermark_seq      BIGINT NOT NULL DEFAULT 0 CHECK (input_watermark_seq >= 0),

  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  PRIMARY KEY (student_id, dimension)
);

CREATE INDEX IF NOT EXISTS personal_model_student_idx
  ON public.personal_model (student_id);

-- `updated_at` maintenance — same shape as every other L2 table in this repo.
CREATE OR REPLACE FUNCTION public.personal_model_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS personal_model_touch_trg ON public.personal_model;
CREATE TRIGGER personal_model_touch_trg
  BEFORE UPDATE ON public.personal_model
  FOR EACH ROW EXECUTE FUNCTION public.personal_model_touch();


-- ═══════════════════════════════════════════════════════════════════════════
-- 4 · RLS — a student may SEE their own model. Writing is §5's problem.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.personal_model_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personal_model         ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS personal_model_signals_select_own ON public.personal_model_signals;
CREATE POLICY personal_model_signals_select_own ON public.personal_model_signals
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

DROP POLICY IF EXISTS personal_model_select_own ON public.personal_model;
CREATE POLICY personal_model_select_own ON public.personal_model
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

-- I.6.a: "Overriding is one action." The student's own write of
-- `explicit_value` is a real UPDATE/INSERT from an `authenticated` session,
-- so RLS admits it — narrowed to the right ROW here, narrowed to the right
-- COLUMN by §5's GRANT.
DROP POLICY IF EXISTS personal_model_upsert_own ON public.personal_model;
CREATE POLICY personal_model_upsert_own ON public.personal_model
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = student_id);

DROP POLICY IF EXISTS personal_model_update_own ON public.personal_model;
CREATE POLICY personal_model_update_own ON public.personal_model
  FOR UPDATE TO authenticated
  USING (auth.uid() = student_id)
  WITH CHECK (auth.uid() = student_id);

-- No policy anywhere admits a client DELETE. `personal_model_signals` is
-- append-only raw evidence (C.3) and `personal_model` is a projection whose
-- only legal removal is a full L2 truncate-and-rebuild (H.2), which runs as
-- the table owner, not a granted role.


-- ═══════════════════════════════════════════════════════════════════════════
-- 5 · THE COLUMN-LEVEL GRANTS — M19-2, V.5.2–V.5.4, ENFORCED HERE
--
-- REVOKE ALL first, on every table, from every role that will touch it —
-- 020's "the REVOKE makes that explicit before the narrow GRANT re-opens one
-- column, so the intent survives a future policy being added by someone who
-- has not read this file" — then re-open exactly the columns each writer is
-- allowed to move.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── `authenticated` — the student ───────────────────────────────────────────
-- RLS already admits INSERT/UPDATE on the student's own row (§4); the GRANT
-- narrows which COLUMNS that row-level permission can move. A student may set
-- their own explicit choice and its timestamp — nothing about the inferred
-- side, which is not theirs to write, only to read and to override.
REVOKE ALL ON public.personal_model FROM authenticated;
GRANT SELECT ON public.personal_model TO authenticated;
GRANT INSERT (student_id, dimension, explicit_value, overridden_at) ON public.personal_model TO authenticated;
GRANT UPDATE (explicit_value, overridden_at) ON public.personal_model TO authenticated;

REVOKE ALL ON public.personal_model_signals FROM authenticated;
GRANT SELECT ON public.personal_model_signals TO authenticated;

-- ── `service_role` — the PREFERENCE_SET projector, and everything else that
-- already trusts it (assessment blueprint reads, exports, etc.) ────────────
-- `service_role` is trusted with the explicit side because it is the role the
-- event-sourced write path (I.6 mechanism 3) actually runs as — the same
-- posture 016 gives `service_role` on `audit_entries` INSERT and 025 gives it
-- on pattern resolution. It also needs the columns below it shares no
-- narrower role for.
REVOKE ALL ON public.personal_model FROM service_role;
GRANT SELECT ON public.personal_model TO service_role;
GRANT INSERT (student_id, dimension, explicit_value, overridden_at,
              input_watermark_event_id, input_watermark_seq) ON public.personal_model TO service_role;
GRANT UPDATE (explicit_value, overridden_at,
              input_watermark_event_id, input_watermark_seq) ON public.personal_model TO service_role;

REVOKE ALL ON public.personal_model_signals FROM service_role;
GRANT SELECT, INSERT ON public.personal_model_signals TO service_role;

-- ── `personal_model_aggregator` — THE INFERENCE ENGINE, AND NOTHING ELSE ───
-- THIS is M19-2's guarantee. Note what is absent from both GRANT lists below:
-- `explicit_value` and `overridden_at` appear in NEITHER. An `UPDATE
-- personal_model SET explicit_value = …` issued by this role fails with
-- Postgres error 42501 (insufficient_privilege) before any row is touched —
-- refused by the database, not by an application check that a future
-- endpoint could forget to call.
DO $$ BEGIN
  CREATE ROLE personal_model_aggregator NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- A LOGIN JWT reaches Postgres via a role that CAN log in; Supabase's
-- `authenticator` role is that role for every JWT-carried claim, the same way
-- it already is for `anon` / `authenticated` / `service_role`. Membership is
-- what lets `authenticator` `SET ROLE personal_model_aggregator` for a JWT
-- whose `role` claim names it — the runtime side (signing that JWT, handing
-- it only to the aggregator job) is outside this file's reach, same as it is
-- for `service_role`'s key.
DO $$ BEGIN
  GRANT personal_model_aggregator TO authenticator;
EXCEPTION WHEN undefined_object THEN NULL; -- local/CI databases without Supabase's `authenticator` role
END $$;

GRANT USAGE ON SCHEMA public TO personal_model_aggregator;

REVOKE ALL ON public.personal_model FROM personal_model_aggregator;
GRANT SELECT ON public.personal_model TO personal_model_aggregator;
GRANT INSERT (student_id, dimension, inferred_value, confidence, evidence_count,
              last_signal_at, input_watermark_event_id, input_watermark_seq)
  ON public.personal_model TO personal_model_aggregator;
GRANT UPDATE (inferred_value, confidence, evidence_count,
              last_signal_at, input_watermark_event_id, input_watermark_seq)
  ON public.personal_model TO personal_model_aggregator;

REVOKE ALL ON public.personal_model_signals FROM personal_model_aggregator;
GRANT SELECT, INSERT ON public.personal_model_signals TO personal_model_aggregator;

-- The aggregator also needs to READ the event stream it extracts signals
-- from — SELECT only, on the table RLS would otherwise hide entirely from a
-- role with no `auth.uid()`. `personal_model_aggregator` is not
-- `service_role` and RLS is NOT disabled for it, so an explicit bypass policy
-- is required, scoped to SELECT alone.
DROP POLICY IF EXISTS academic_events_aggregator_select ON public.academic_events;
CREATE POLICY academic_events_aggregator_select ON public.academic_events
  FOR SELECT TO personal_model_aggregator USING (true);


-- ═══════════════════════════════════════════════════════════════════════════
-- 6 · A BELT-AND-BRACES TRIGGER — the same column can never move under this
-- role even if a future `GRANT` mistakenly widens it.
--
-- §5 is sufficient by itself (an UPDATE naming a column the caller has no
-- privilege on is refused before the trigger ever runs). This trigger is the
-- second, INDEPENDENT mechanism 020 §5 and 025 §7 both keep alongside their
-- own grants: "RLS does not bind the service role... this stops the next
-- endpoint somebody writes" — here, the next GRANT somebody writes.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.personal_model_explicit_is_sacred()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF current_user = 'personal_model_aggregator' THEN
    IF TG_OP = 'UPDATE' AND (
      NEW.explicit_value IS DISTINCT FROM OLD.explicit_value
      OR NEW.overridden_at IS DISTINCT FROM OLD.overridden_at
    ) THEN
      RAISE EXCEPTION 'personal_model_aggregator may not write explicit_value or overridden_at (I.6 / M19-2)';
    END IF;
    IF TG_OP = 'INSERT' AND (NEW.explicit_value IS NOT NULL OR NEW.overridden_at IS NOT NULL) THEN
      RAISE EXCEPTION 'personal_model_aggregator may not write explicit_value or overridden_at (I.6 / M19-2)';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS personal_model_explicit_is_sacred_trg ON public.personal_model;
CREATE TRIGGER personal_model_explicit_is_sacred_trg
  BEFORE INSERT OR UPDATE ON public.personal_model
  FOR EACH ROW EXECUTE FUNCTION public.personal_model_explicit_is_sacred();


-- ═══════════════════════════════════════════════════════════════════════════
-- WHAT THIS FILE DELIBERATELY DOES NOT DO
--
-- · No default VALUE is stored anywhere in SQL. I.5's "the system falls back
--   to the product default and says so" is `resolveEffectiveValue()` in
--   `lib/personal-model.ts` — a product-layer decision, not a schema one,
--   because the disclosed MESSAGE is what V.5.7 actually requires and a
--   generated column cannot hold a sentence that varies by dimension.
-- · No DECAY is computed or stored here. I.5: "Decay is applied at read
--   time... no row is ever rewritten to age it." `confidence` is exactly what
--   the aggregator observed; `decayedConfidence()` derives the read-time
--   figure from it and `last_signal_at`, in TypeScript, on every read.
-- · No new event table. `PREFERENCE_SET` already exists as an
--   `academic_events.event_type` value (015 §2) with a required payload of
--   `{dimension, value}` (`lib/event-contract.ts:REQUIRED_PAYLOAD_KEYS`).
--   M19-4's replay reads THAT stream; this file adds no second one.
-- ═══════════════════════════════════════════════════════════════════════════

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '031',
  '031_personal_model.sql',
  '139fdf380621cde2abfe3dae5e667fe87e46f1e81c45b605817671e4ca43587b',
  'self'
);

-- ─── 032_recommendations.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 032_recommendations.sql   ·   M20
--
-- EXECUTION_PLAN M20:
--   M20-1  Candidate generation, priority, decay. Done when: K.1, K.2, K.7.
--   M20-2  Mandatory `evidence_refs`; a recommendation with none CANNOT BE
--          INSERTED. Done when: V.7.4.
--   M20-3  "Guide, never gate" enforced mechanically. Done when: K.3 — the
--          next action cannot gate anything (V.11).
--   M20-4  Outcome tracking; escalation without shaming. Done when: K.5, K.6.
--
-- Architecture Part K in full; C.3 `Recommendation` / `RecommendationOutcome`;
-- B.11 (Recommendation Engine).
--
-- NOT APPLIED to any database. Same posture as every migration since 015.
--
--
-- WHAT THIS FILE ADDS, AND WHY IT IS ONE FILE
--
--   1 · recommendation_kind / recommendation_state /
--       recommendation_outcome_kind    Bounded enums. K.1's candidate-kind
--                                       table, C.3's state list, and C.3's
--                                       outcome list, transcribed exactly —
--                                       mirrored in `lib/recommendations/
--                                       types.ts` and cross-checked by
--                                       `tests/recommendations.test.mjs`, the
--                                       same discipline 031 uses for
--                                       `personal_model_dimension`.
--   2 · recommendations                C.3 `Recommendation`. `evidence_refs`
--                                       is NOT NULL with a `cardinality(...)
--                                       >= 1` CHECK — B.11's "a recommendation
--                                       with no evidence reference is a bug"
--                                       made structural (V.7.4). No `blocks`
--                                       column, no `required` column, no
--                                       gating field of any kind exists on
--                                       this table — K.3's "there is no
--                                       `blocks` field, no `required` flag"
--                                       is an ABSENCE, not a rule text can
--                                       violate.
--   3 · recommendation_outcomes        C.3 `RecommendationOutcome` — raw
--                                       evidence about the system, append-
--                                       only, the same three-layer refusal
--                                       024/030 already use for their own
--                                       append-only tables.
--   4 · THE GRANTS                     K.3's "the recommendations table is
--                                       read-only to every subsystem except
--                                       the Recommendation Engine and the
--                                       outcome-recording path" — both of
--                                       which run server-side as
--                                       `service_role`, the same posture
--                                       024/029/030 already use for every
--                                       write a client must never make
--                                       directly. `authenticated` gets SELECT
--                                       only: a student may always SEE their
--                                       own recommendations, and may never
--                                       write a row that could be mistaken
--                                       for a gate.
--
-- ADDITIVE ONLY. Idempotent; safe to re-run. Run in: Supabase → SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · THE BOUNDED ENUMS (M20-1, K.1, C.3)
--
-- `recommendation_kind` transcribes K.1's candidate-kind table, one value per
-- row of that table's "Candidate kinds" column. Adding an eleventh kind is a
-- migration and a code change in `lib/recommendations/types.ts`, the same
-- deliberate friction 031 §1 chose for `personal_model_dimension` — this list
-- grows by decision, never silently.
-- ═══════════════════════════════════════════════════════════════════════════

DO $$ BEGIN
  CREATE TYPE public.recommendation_kind AS ENUM (
    'work_open_pattern',
    'take_due_retest',
    'pattern_recurred',
    'verify_unverified_session',
    'coverage_hole',
    'subject_no_proven_concept',
    'concept_decaying',
    'exam_weak_coverage',
    'dormant_session_reaping',
    'personal_model_confirm',
    'correction_request_pending'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE public.recommendation_kind IS
  'K.1''s candidate-kind table, transcribed. Mirrors RECOMMENDATION_KINDS in '
  'lib/recommendations/types.ts; tests/recommendations.test.mjs asserts the '
  'two never drift.';

DO $$ BEGIN
  CREATE TYPE public.recommendation_state AS ENUM (
    'active', 'dismissed', 'ignored', 'superseded', 'acted_on', 'expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE public.recommendation_state IS
  'C.3 Recommendation.state, verbatim. K.4 defines every transition.';

DO $$ BEGIN
  CREATE TYPE public.recommendation_outcome_kind AS ENUM (
    'acted_on', 'dismissed', 'ignored_expired', 'superseded'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE public.recommendation_outcome_kind IS
  'C.3 RecommendationOutcome.outcome, verbatim.';


-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · `recommendations` — C.3, DERIVED STATE
--
-- V.7.4, made structural: `evidence_refs` is NOT NULL, and
-- `cardinality(evidence_refs) >= 1` is CHECKed rather than
-- `array_length(evidence_refs, 1) >= 1` — Postgres's `array_length()` returns
-- NULL (not 0) for a zero-length array, which would make an empty-but-
-- non-null `evidence_refs` slip past an `array_length >= 1` CHECK silently.
-- `cardinality()` returns 0 for an empty array, so the CHECK actually fires.
-- This is the exact bug class M8–M11's own "reject not degrade" convention
-- exists to close.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.recommendations (
  recommendation_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  kind              public.recommendation_kind NOT NULL,
  subject           TEXT,
  concept_id        UUID        REFERENCES public.concepts(id) ON DELETE SET NULL,
  pattern_id        UUID        REFERENCES public.patterns(id) ON DELETE SET NULL,

  priority          NUMERIC     NOT NULL,
  reason_template   TEXT        NOT NULL CHECK (length(trim(reason_template)) > 0),

  -- B.11 / V.7.4 — THE STRUCTURAL REFUSAL. NOT NULL alone rejects a bare
  -- NULL; the CHECK additionally rejects an empty array, which NOT NULL
  -- alone would not catch.
  evidence_refs     JSONB[]     NOT NULL,

  -- K.3 — deliberately absent from this table: any column named `blocks`,
  -- `required`, `gates`, `locks`, or similar. A recommendation has no write
  -- access to any other subsystem's state and no field that could carry one.

  state             public.recommendation_state NOT NULL DEFAULT 'active',
  surfaced_count    INTEGER     NOT NULL DEFAULT 0 CHECK (surfaced_count >= 0),

  -- K.4/K.7 — dedupe within the active set, and cooling after close.
  dedupe_key        TEXT        NOT NULL CHECK (length(trim(dedupe_key)) > 0),

  expires_at        TIMESTAMPTZ NOT NULL,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT recommendations_evidence_refs_nonempty
    CHECK (cardinality(evidence_refs) >= 1)
);

-- C.3's identity: at most one ACTIVE recommendation per (student, dedupe_key)
-- — this is what "the dedupe_key is suppressed for a cooling window" (K.4)
-- rests on: a second candidate for the same underlying condition cannot
-- create a second active row while the first is still open.
CREATE UNIQUE INDEX IF NOT EXISTS recommendations_student_dedupe_active_idx
  ON public.recommendations (student_id, dedupe_key) WHERE state = 'active';

CREATE INDEX IF NOT EXISTS recommendations_student_state_idx
  ON public.recommendations (student_id, state, priority DESC);
CREATE INDEX IF NOT EXISTS recommendations_expires_idx
  ON public.recommendations (expires_at) WHERE state = 'active';

COMMENT ON TABLE public.recommendations IS
  'C.3 Recommendation. evidence_refs is NOT NULL with a cardinality >= 1 '
  'CHECK — B.11''s "a recommendation with no evidence reference is a bug" '
  'made structural (V.7.4). No blocks/required/gates column exists anywhere '
  'in this table (K.3).';

CREATE OR REPLACE FUNCTION public.recommendations_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS recommendations_touch_trg ON public.recommendations;
CREATE TRIGGER recommendations_touch_trg
  BEFORE UPDATE ON public.recommendations
  FOR EACH ROW EXECUTE FUNCTION public.recommendations_touch();

-- K.4 — once a recommendation leaves `active`, it is CLOSED. Its terminal
-- state (dismissed / ignored / superseded / acted_on / expired) is never
-- reopened and never overwritten by a later transition — "the row is closed
-- ..., never silently deleted, because the sequence of what was suggested
-- and what actually happened is how K.8 learns." Re-deriving the same
-- underlying condition creates a NEW row with a new `recommendation_id`
-- once the dedupe_key's cooling window (K.7) has elapsed; it never mutates
-- a closed one.
CREATE OR REPLACE FUNCTION public.recommendations_state_is_append_only()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.state <> 'active' AND NEW.state IS DISTINCT FROM OLD.state THEN
    RAISE EXCEPTION
      'recommendation %: state is closed (%) and cannot transition again (K.4)',
      OLD.recommendation_id, OLD.state;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS recommendations_state_is_append_only_trg ON public.recommendations;
CREATE TRIGGER recommendations_state_is_append_only_trg
  BEFORE UPDATE ON public.recommendations
  FOR EACH ROW EXECUTE FUNCTION public.recommendations_state_is_append_only();


-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · `recommendation_outcomes` — C.3, RAW EVIDENCE, APPEND-ONLY (K.6)
--
-- "Every recommendation closes with a RecommendationOutcome... so 'do our
-- recommendations actually close gaps for this student?' is answerable from
-- data. That is the feedback loop that lets correction_method become an
-- evidenced dimension of the Personal Model." This table is that evidence,
-- and it is append-only for the same reason 024/030's evidence tables are:
-- a system that can edit its own outcome history cannot prove it learned
-- anything.
--
-- `resulting_session_id` / `resulting_resolution_id` carry no FK, the same
-- trade `personal_model_signals.source_event_id` (031 §2) makes for a
-- partitioned target — `study_sessions` and `mistake_resolutions` are not
-- partitioned, but pointing this table at either would make
-- recommendation_outcomes' own append-only guarantee load-bearing for
-- referential integrity on two OTHER subsystems' primary keys, which is a
-- coupling this table does not need: existence is the writer's
-- responsibility, not this table's.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.recommendation_outcomes (
  outcome_id             UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  recommendation_id      UUID        NOT NULL REFERENCES public.recommendations(recommendation_id) ON DELETE RESTRICT,

  outcome                public.recommendation_outcome_kind NOT NULL,
  at                     TIMESTAMPTZ NOT NULL,

  resulting_session_id     UUID,
  resulting_resolution_id  UUID,
  benefit_observed          NUMERIC,

  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recommendation_outcomes_recommendation_idx
  ON public.recommendation_outcomes (recommendation_id, at DESC);

COMMENT ON TABLE public.recommendation_outcomes IS
  'C.3 RecommendationOutcome. Append-only raw evidence — K.6''s feedback '
  'loop. Never recomputed away.';

-- Append-only, three layers, same posture as 024 §6 / 030 §5:
--   (a) no UPDATE/DELETE policy is ever granted to `authenticated` (§4);
--   (b) an explicit REVOKE closes the client-library path for every role;
--   (c) a trigger refuses UPDATE/DELETE outright, because RLS does not bind
--       `service_role` and every server write in this codebase runs as it.
CREATE OR REPLACE FUNCTION public.recommendation_outcomes_append_only()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'recommendation_outcomes is append-only (K.6) — % is not permitted', TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS recommendation_outcomes_no_update_trg ON public.recommendation_outcomes;
CREATE TRIGGER recommendation_outcomes_no_update_trg
  BEFORE UPDATE ON public.recommendation_outcomes
  FOR EACH ROW EXECUTE FUNCTION public.recommendation_outcomes_append_only();

DROP TRIGGER IF EXISTS recommendation_outcomes_no_delete_trg ON public.recommendation_outcomes;
CREATE TRIGGER recommendation_outcomes_no_delete_trg
  BEFORE DELETE ON public.recommendation_outcomes
  FOR EACH ROW EXECUTE FUNCTION public.recommendation_outcomes_append_only();


-- ═══════════════════════════════════════════════════════════════════════════
-- 4 · RLS — a student may SEE their own recommendations and outcomes.
-- Writing is §5's problem, and §5 gives writing to `service_role` alone.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.recommendations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendation_outcomes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS recommendations_select_own ON public.recommendations;
CREATE POLICY recommendations_select_own ON public.recommendations
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

DROP POLICY IF EXISTS recommendation_outcomes_select_own ON public.recommendation_outcomes;
CREATE POLICY recommendation_outcomes_select_own ON public.recommendation_outcomes
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.recommendations r
      WHERE r.recommendation_id = recommendation_outcomes.recommendation_id
        AND r.student_id = auth.uid()
    )
  );

-- No INSERT/UPDATE/DELETE policy for `authenticated` on either table — every
-- write (candidate insertion, dismissal, outcome recording, decay/expiry) is
-- server-side, under the student's identity taken from their verified
-- session, never from a request body (D.1.a). This is also HOW K.3's "no
-- code path through which a recommendation could gate anything" is made a
-- database-level guarantee rather than a promise about application code: a
-- client cannot write this table at all, gate-shaped or otherwise.


-- ═══════════════════════════════════════════════════════════════════════════
-- 5 · THE GRANTS — K.3, "read-only to every subsystem except the
-- Recommendation Engine and the outcome-recording path"
-- ═══════════════════════════════════════════════════════════════════════════

REVOKE ALL ON public.recommendations FROM authenticated;
GRANT SELECT ON public.recommendations TO authenticated;

REVOKE ALL ON public.recommendation_outcomes FROM authenticated;
GRANT SELECT ON public.recommendation_outcomes TO authenticated;

-- `service_role` is the Recommendation Engine and the outcome-recording
-- path, both of which run server-side (`lib/recommendations/*.ts` behind
-- `app/api/recommendations/**`), the same posture every other L2 writer in
-- this codebase already uses.
REVOKE ALL ON public.recommendations FROM service_role;
GRANT SELECT, INSERT, UPDATE ON public.recommendations TO service_role;
-- No DELETE grant, to either role — K.4: "never silently deleted."

REVOKE ALL ON public.recommendation_outcomes FROM service_role;
GRANT SELECT, INSERT ON public.recommendation_outcomes TO service_role;
-- No UPDATE/DELETE grant — §3's trigger is belt-and-braces on top of this.


-- ═══════════════════════════════════════════════════════════════════════════
-- WHAT THIS FILE DELIBERATELY DOES NOT DO
--
-- · No `blocks`, `required`, `locks`, or `gates` column, anywhere. K.3's
--   guarantee is an absence, and an absence cannot be a bug fixed later by a
--   forgotten `if` — there is nothing for a forgotten `if` to read.
-- · No default priority formula, no decay computation, in SQL. K.2/K.7 are
--   TypeScript-side, pure and deterministic
--   (`lib/recommendations/engine.ts`), read here only as the two columns
--   (`priority`, `expires_at`) their output is written into — the same
--   split 031 draws between `resolveEffectiveValue()` (TypeScript) and the
--   columns it resolves from (SQL).
-- · No AI write path. B.11: "AI may rewrite the phrasing... AI may not add,
--   remove or reorder candidates." Nothing in this file grants an AI-facing
--   role any access to this table at all.
-- ═══════════════════════════════════════════════════════════════════════════

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '032',
  '032_recommendations.sql',
  '91d3f637aecc0850cc2b9cd1d085435d318de3279afeb1f0dc74fdb4605e882b',
  'self'
);

-- ─── 033_today.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 033_today.sql   ·   M21-1 / M21-3
--
-- WHAT THIS CLOSES
--
-- Architecture Part L (Today Engine); B.12: *"Today owns no facts. It is a
-- projection with a cache and one durable field, `students.last_seen_at`."*
-- L.5: *"`last_seen_at` advances only when Today is actually rendered … An
-- accomplishment is shown once and then moves into the record — it does not
-- persist as a badge."*
--
-- This migration adds exactly the one durable field B.12 names, and exactly
-- one write path for it — the same "read-then-append under a lock" shape
-- `012_students_and_profiles.sql §5` (`set_student_profile`) already
-- established, because the hazard is the same one: a whole-row read-
-- modify-write from the client would race the same way `user_data` used to.
--
-- ADDITIVE ONLY. One column on `students` (012), one function. Nothing
-- existing is touched.
--
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- NOT APPLIED to any database by the milestone that wrote it.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. `students.last_seen_at` — B.12's one durable field ──────────────────
--
-- NULL means "Today has never been rendered for this student" — L.4's
-- `no_evidence_yet` / a brand-new account reads this as "everything since the
-- beginning of time is new", which `lib/today/engine.ts`'s
-- `accomplishmentsSince()` implements as `since = lastSeenAtMs ?? -Infinity`.
-- It is NOT defaulted to `now()` on creation, because a default of "now" would
-- silently hide every accomplishment that happened between account creation
-- and first Today render — exactly the kind of silent loss 012's profile chain
-- exists to prevent, one table over.
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

COMMENT ON COLUMN students.last_seen_at IS
  'B.12 / L.5. The one durable field the Today Engine owns. Advances only when Today is actually rendered, via public.mark_today_seen() — never by a client UPDATE. NULL means Today has never been rendered for this student.';

-- ── 2. `mark_today_seen()` — the ONLY write path for `last_seen_at` ────────
--
-- Returns the PREVIOUS value (before this call), because that is exactly what
-- the caller needs: `lib/today/engine.ts` computes "what changed since I was
-- last here" from the OLD `last_seen_at`, and only after that computation is
-- complete does the caller advance the row to `now()`. Reading the old value
-- and writing the new one in ONE function call, under ONE lock, is what makes
-- "read old, then write new" atomic — the same reasoning `set_student_profile`
-- gives for locking the identity row before it reads `is_current`.
--
-- `p_now` defaults to `now()`; a caller may pass an explicit timestamp only
-- for deterministic testing against a live database, never to backdate a
-- student's own visit.
CREATE OR REPLACE FUNCTION public.mark_today_seen(p_now TIMESTAMPTZ DEFAULT NULL)
RETURNS TABLE (previous_last_seen_at TIMESTAMPTZ, new_last_seen_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_old TIMESTAMPTZ;
  v_new TIMESTAMPTZ := COALESCE(p_now, now());
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'mark_today_seen: no authenticated caller'
      USING ERRCODE = '28000';
  END IF;

  PERFORM public.ensure_student();

  SELECT last_seen_at INTO v_old FROM students
   WHERE student_id = v_uid
     FOR UPDATE;

  UPDATE students SET last_seen_at = v_new WHERE student_id = v_uid;

  RETURN QUERY SELECT v_old, v_new;
END;
$$;

REVOKE ALL     ON FUNCTION public.mark_today_seen(TIMESTAMPTZ) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.mark_today_seen(TIMESTAMPTZ) TO authenticated, service_role;

COMMENT ON FUNCTION public.mark_today_seen(TIMESTAMPTZ) IS
  'The only write path for students.last_seen_at (M21-3, L.5). Reads the prior value and advances to now() under FOR UPDATE on the caller''s own students row, in one transaction — so "what is new since last render" and "the render happened" cannot race. Called once per Today render, after the response is built, never before.';

-- ── 3. Verification the founder can run after applying this file ──────────
DO $$
DECLARE
  n_col INT;
BEGIN
  SELECT count(*) INTO n_col
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'students' AND column_name = 'last_seen_at';

  IF n_col <> 1 THEN
    RAISE EXCEPTION 'students.last_seen_at was not created';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = 'mark_today_seen'
  ) THEN
    RAISE EXCEPTION 'public.mark_today_seen() was not created';
  END IF;

  RAISE NOTICE 'M21: students.last_seen_at present, mark_today_seen() installed.';
END $$;

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '033',
  '033_today.sql',
  'cf0f473bdf4a54b6d38346156b70e2cba50960f410b6ef28d84af5f8fcc954d4',
  'self'
);

-- ─── 034_home_layout.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 034_home_layout.sql   ·   M22-2 / M22-3
--
-- WHAT THIS CLOSES
--
-- Architecture Part M (Home composition) in full; Part S.6's REBUILD note for
-- `lib/dash-layout.ts`; EXECUTION_PLAN M22-2 ("Server-persisted HomeLayout
-- replacing 5 unsynced booleans... Done when: layout survives a device
-- change") and M22-3 ("Four importance tiers + the anti-inflation guardrails
-- ... Done when: M.5 — 'critical' cannot inflate").
--
-- CURRENT FACT this replaces: `localStorage["ledger-dash-layout"]` — five
-- untyped booleans, unsynced, device-local, no ordering, no sizing, no
-- registry, no importance channel (M.2's "CURRENT FACT — the gap").
--
-- TWO TABLES, TWO TRUST LEVELS — the same split 031 §"WHY A NEW ROLE" draws
-- for the Personal Model, applied to Home:
--
--   1. home_layout                 the STUDENT's data (M.1: "which
--                                   components are visible, in what order,
--                                   at what size" is the student's). One row
--                                   per student. The student may read AND
--                                   write their own row in full.
--
--   2. home_importance_promotions  the SYSTEM's data (M.1: "what is critical
--                                   enough to override the student's order"
--                                   is the system's, under M.5). Append-only.
--                                   The student may READ their own rows (M.5
--                                   .5's "promotion frequency is measurable")
--                                   but has NO write path at all — enforced
--                                   by GRANT, not by application code, which
--                                   is exactly what makes M22-3's own done-
--                                   when ("'critical' cannot inflate") true
--                                   at the database layer, not just in
--                                   `lib/home/importance.ts`. A hand-crafted
--                                   INSERT from an authenticated session
--                                   attempting to self-promote any component
--                                   to `critical` fails with Postgres error
--                                   42501 before a row is touched — the same
--                                   guarantee 031 §5 gives
--                                   `personal_model_aggregator` over
--                                   `explicit_value`, mirrored here for the
--                                   student over `home_importance_promotions`
--                                   in its entirety.
--
-- NOT APPLIED to any database. Same posture as every migration since 015.
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · home_layout — THE STUDENT'S DATA (M22-2)
--
-- `entries` is the whole `HomeLayout.entries` array (`lib/home/types.ts`) as
-- JSONB — one row, one document, matching the shape the client already
-- validates client-side (`validateHomeLayout`) and the server re-validates
-- before every write (`app/api/home-layout/route.ts` calls the same
-- function — never trusts the client's own validation alone).
--
-- Why JSONB and not one row per (student, component): a `HomeLayout` is read
-- and written as ONE unit — "the merge is a pure function... given the same
-- three inputs it always produces the same layout" (M.3) reads the whole
-- document, never a single component's row. A five-row table would need a
-- transaction to keep "order" consistent across a reorder; one JSONB column,
-- written whole, cannot half-apply.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.home_layout (
  student_id  UUID        NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  entries     JSONB       NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(entries) = 'array'),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.home_layout IS
  'M22-2. One row per student — the server-persisted HomeLayout that replaces localStorage["ledger-dash-layout"]. Visibility/order/size ONLY; importance/tier is never stored here (see home_importance_promotions) — the student owns layout, the system owns importance (M.1), and this table is physically incapable of expressing the latter.';

-- `updated_at` maintenance — same shape as every other student-owned table
-- in this repo (e.g. 031's `personal_model_touch`).
CREATE OR REPLACE FUNCTION public.home_layout_touch()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS home_layout_touch_trg ON public.home_layout;
CREATE TRIGGER home_layout_touch_trg
  BEFORE UPDATE ON public.home_layout
  FOR EACH ROW EXECUTE FUNCTION public.home_layout_touch();

-- ── M.2's one hard rule, enforced a second time here ────────────────────────
-- `lib/home/layout.ts`'s `validateHomeLayout` already refuses a submitted
-- layout that hides the Score before it ever reaches this table. This
-- trigger is the belt-and-braces twin (same posture 031 §6's
-- `personal_model_explicit_is_sacred` documents): even a future write path
-- that forgets to call the application validator cannot persist
-- `{"componentId":"score", ..., "visible": false}` — the row is rejected by
-- the database itself.
CREATE OR REPLACE FUNCTION public.home_layout_score_is_chrome()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(NEW.entries) AS e
    WHERE e ->> 'componentId' = 'score' AND (e ->> 'visible') = 'false'
  ) THEN
    RAISE EXCEPTION 'home_layout: componentId "score" cannot be hidden — it is persistent chrome (M.2)'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS home_layout_score_is_chrome_trg ON public.home_layout;
CREATE TRIGGER home_layout_score_is_chrome_trg
  BEFORE INSERT OR UPDATE ON public.home_layout
  FOR EACH ROW EXECUTE FUNCTION public.home_layout_score_is_chrome();

ALTER TABLE public.home_layout ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS home_layout_select_own ON public.home_layout;
CREATE POLICY home_layout_select_own ON public.home_layout
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

DROP POLICY IF EXISTS home_layout_upsert_own ON public.home_layout;
CREATE POLICY home_layout_upsert_own ON public.home_layout
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = student_id);

DROP POLICY IF EXISTS home_layout_update_own ON public.home_layout;
CREATE POLICY home_layout_update_own ON public.home_layout
  FOR UPDATE TO authenticated
  USING (auth.uid() = student_id)
  WITH CHECK (auth.uid() = student_id);

-- No DELETE policy — a student who wants defaults back submits the registry
-- defaults as their layout (an UPDATE), same as every other "reset" in this
-- codebase; the row itself is never removed except by the ON DELETE CASCADE
-- from auth.users (account deletion, Part O).

REVOKE ALL ON public.home_layout FROM authenticated;
GRANT SELECT ON public.home_layout TO authenticated;
GRANT INSERT (student_id, entries) ON public.home_layout TO authenticated;
GRANT UPDATE (entries) ON public.home_layout TO authenticated;

REVOKE ALL ON public.home_layout FROM service_role;
GRANT SELECT, INSERT, UPDATE ON public.home_layout TO service_role;


-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · home_importance_promotions — THE SYSTEM'S DATA (M22-3, M.5.5)
--
-- Append-only. `tier` excludes 'ambient' by construction — ambient is the
-- implicit default and is never itself a promotion (mirrors
-- `lib/home/types.ts`'s `HomeImportancePromotion.tier` type,
-- `Exclude<HomeImportanceTier, "ambient">`).
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.home_importance_promotions (
  promotion_id    UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  component_id    TEXT        NOT NULL CHECK (component_id IN ('score','recommendation','recent_activity','exams','features')),
  tier            TEXT        NOT NULL CHECK (tier IN ('highlighted','promoted','critical')),
  trigger         TEXT        NOT NULL,
  evidence_refs   JSONB       NOT NULL CHECK (jsonb_typeof(evidence_refs) = 'array' AND jsonb_array_length(evidence_refs) >= 1),
  promoted_at     TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.home_importance_promotions IS
  'M22-3 / M.5.5. Append-only log of every promotion above ambient, with trigger and evidence — "promotion frequency is measurable and regressions are visible." Written ONLY by service_role (the home-layout API route, after lib/home/importance.ts resolves signals server-side). A student may SELECT their own rows and may not INSERT/UPDATE/DELETE at all — the GRANT below is the structural half of "critical cannot inflate": there is no path from an authenticated session to this table except reading it.';

CREATE INDEX IF NOT EXISTS home_importance_promotions_student_idx
  ON public.home_importance_promotions (student_id, promoted_at DESC);

ALTER TABLE public.home_importance_promotions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS home_importance_promotions_select_own ON public.home_importance_promotions;
CREATE POLICY home_importance_promotions_select_own ON public.home_importance_promotions
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

-- Deliberately NO INSERT/UPDATE/DELETE policy for `authenticated`. RLS
-- defaults to deny; the REVOKE below removes the privilege at the GRANT
-- layer too (belt-and-braces, same posture 020/025/031 use elsewhere), so
-- even a future permissive policy authored without reading this comment
-- still meets a table-level REVOKE that must be separately, deliberately
-- reversed.
REVOKE ALL ON public.home_importance_promotions FROM authenticated;
GRANT SELECT ON public.home_importance_promotions TO authenticated;

REVOKE ALL ON public.home_importance_promotions FROM service_role;
GRANT SELECT, INSERT ON public.home_importance_promotions TO service_role;
-- No UPDATE, no DELETE, for anyone — append-only, matching
-- `personal_model_signals` (031) and `audit_entries` (016).


-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · Verification the founder can run after applying this file
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  n_tbl INT;
BEGIN
  SELECT count(*) INTO n_tbl FROM information_schema.tables
  WHERE table_schema = 'public' AND table_name IN ('home_layout', 'home_importance_promotions');
  IF n_tbl <> 2 THEN
    RAISE EXCEPTION '034: expected 2 tables (home_layout, home_importance_promotions), found %', n_tbl;
  END IF;

  -- The anti-inflation grant, checked directly rather than trusted: `authenticated`
  -- must have SELECT and nothing else on the promotions table.
  IF EXISTS (
    SELECT 1 FROM information_schema.role_table_grants
    WHERE table_schema = 'public' AND table_name = 'home_importance_promotions'
      AND grantee = 'authenticated' AND privilege_type <> 'SELECT'
  ) THEN
    RAISE EXCEPTION '034: authenticated has a privilege beyond SELECT on home_importance_promotions — the anti-inflation guarantee is broken';
  END IF;

  RAISE NOTICE '034: home_layout + home_importance_promotions installed; authenticated write path to promotions confirmed absent.';
END $$;

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '034',
  '034_home_layout.sql',
  '9c77396bb61e70612355c16429df02162860a992c2a7e52e1fecba3d1f7f4cc7',
  'self'
);

-- ─── 035_academic_memory_search.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 035_academic_memory_search.sql   ·   M23-1
--
-- WHAT THIS CLOSES
--
-- Architecture Part H.3 ("Indexing and search") and EXECUTION_PLAN M23-1:
-- *"Five-layer indexing; FTS + pgvector — no separate search service (U.2)."*
--
-- H.3 IS NOT A NEW DATASTORE. It is three indexes over the SAME Postgres the
-- rest of the product already writes to:
--
--   1. Structured — B-tree/composite indexes matching the query shapes. This
--      one is ALREADY DONE. `occurrences_concept_idx`, `patterns_leaf_
--      severity_idx` (007_mistakes.sql:301,209), `academic_record_studied_
--      not_assessed_idx` (026), `academic_events_concept_idx` (015) already
--      cover the query shapes H.4's five example questions need. Nothing new
--      is added here for that reason.
--
--   2. Lexical — Postgres `tsvector` over `declared_text`, question stems,
--      concept labels, marker notes. NEW, this migration.
--
--   3. Semantic — `pgvector` embeddings over concept labels and declaration
--      text ONLY. Deliberately NOT over answers or evidence content: H.3's own
--      words — *"embedding the student's own wrong answers creates a
--      similarity surface with no academic query behind it and a real privacy
--      cost."* NEW, this migration.
--
-- `CREATE EXTENSION IF NOT EXISTS vector` is the one new capability this
-- database gains. Nothing else does — there is no second service, no second
-- source of truth for "what exists" (H.1.a), and the index is rebuildable
-- from L1 exactly the way H.3 requires: `search_vector` columns are
-- GENERATED ALWAYS, so a lexical index needs no backfill job and cannot drift
-- from the row it describes. The `*_embedding` columns are plain nullable
-- `vector` columns rather than generated, because an embedding requires a
-- model call this migration does not make (see the note at the bottom).
--
-- THIS FILE IS WRITTEN, NOT APPLIED (M23's ground rules). Verified structurally
-- by tests/academic-memory.test.mjs — the same posture tests/data-ownership
-- .test.mjs and tests/recommendations.test.mjs take for prior migrations: the
-- SQL text is read and asserted against, because there is no live database in
-- this environment to run it against.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── pgvector, guarded ────────────────────────────────────────────────────────
-- IF NOT EXISTS: some Supabase projects ship pgvector pre-enabled for other
-- reasons. This statement is a no-op on those, and the only new capability on
-- everything else.
CREATE EXTENSION IF NOT EXISTS vector;

-- ═══════════════════════════════════════════════════════════════════════════
-- LEXICAL — tsvector + GIN, one per H.3's named field
-- ═══════════════════════════════════════════════════════════════════════════

-- `concepts` — "concept labels". One generated column over the full display
-- path (subject → chapter → topic → name), because a student's own words for
-- a concept rarely match only the leaf name ("the wobbling top thing" hits
-- `topic`, not `name`).
ALTER TABLE public.concepts
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(topic, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(chapter, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(subject, '')), 'D')
  ) STORED;

CREATE INDEX IF NOT EXISTS concepts_search_vector_idx
  ON public.concepts USING GIN (search_vector);

-- `session_concepts.declared_text` — "declaration text", the student's own
-- words (022's V.2.1: immutable once written). NULL-tolerant: a resolved
-- session_concept with no declared_text produces a NULL tsvector, which GIN
-- simply omits, exactly the H.1.a-consistent behaviour — the index describes
-- what is there and invents nothing for what is not.
ALTER TABLE public.session_concepts
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(declared_text, ''))) STORED;

CREATE INDEX IF NOT EXISTS session_concepts_search_vector_idx
  ON public.session_concepts USING GIN (search_vector);

-- `academic_events.declared_text` — the same field, at the event layer (L1).
-- `session_concepts` is L2 (derived, rebuildable); this is the L1 fact it was
-- built from, so both carry the index rather than only the derivation, per
-- H.1.a's "may read downward" — a query answered from L1 directly does not
-- need L2 to exist first.
ALTER TABLE public.academic_events
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(declared_text, ''))) STORED;

CREATE INDEX IF NOT EXISTS academic_events_search_vector_idx
  ON public.academic_events USING GIN (search_vector);

-- `assessment_questions.stem` — "question stems".
ALTER TABLE public.assessment_questions
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(stem, ''))) STORED;

CREATE INDEX IF NOT EXISTS assessment_questions_search_vector_idx
  ON public.assessment_questions USING GIN (search_vector);

-- `occurrences.marker_note` — "marker notes". `topic` is already covered by
-- the structured `occurrences_concept_idx` and by `concepts.search_vector`
-- through the FK, so only the free-text marker note is new here.
ALTER TABLE public.occurrences
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(marker_note, ''))) STORED;

CREATE INDEX IF NOT EXISTS occurrences_search_vector_idx
  ON public.occurrences USING GIN (search_vector);

-- ═══════════════════════════════════════════════════════════════════════════
-- SEMANTIC — pgvector, over concept labels and declaration text ONLY (H.3)
--
-- 1536 dims: a conventional embedding width (matches, e.g., OpenAI
-- text-embedding-3-small and Voyage's `voyage-2` family) and NOT a figure
-- read off any embedding model already configured in this codebase — none
-- is, today (`lib/concept-resolution.ts:26-36` explains why concept
-- resolution deliberately stayed lexical rather than embedding-based). The
-- width is a placeholder the population job (below) must match to whichever
-- embedding model it actually calls; `vector(1536)` is not a commitment to a
-- specific provider. Nullable — an embedding is not knowable without a model
-- call, and H.1.a forbids this migration from fabricating one. Population is
-- a follow-on job (noted at the bottom of this file); querying and indexing
-- are ready the moment it runs.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.concepts
  ADD COLUMN IF NOT EXISTS label_embedding vector(1536);

ALTER TABLE public.session_concepts
  ADD COLUMN IF NOT EXISTS declared_text_embedding vector(1536);

-- IVFFlat over cosine distance. `lists = 100` is the pgvector-recommended
-- starting point for a table in the tens-of-thousands-of-rows range this
-- product's concept taxonomy and per-student declarations sit in; re-tuning
-- `lists` as the table grows is an operational change, not a schema one.
-- `WHERE ... IS NOT NULL` because IVFFlat is built over populated rows only —
-- an index over an all-NULL column at migration time is legal but useless,
-- and Postgres will happily maintain it as rows are populated later.
CREATE INDEX IF NOT EXISTS concepts_label_embedding_idx
  ON public.concepts USING ivfflat (label_embedding vector_cosine_ops)
  WITH (lists = 100);

CREATE INDEX IF NOT EXISTS session_concepts_declared_text_embedding_idx
  ON public.session_concepts USING ivfflat (declared_text_embedding vector_cosine_ops)
  WITH (lists = 100);

-- ═══════════════════════════════════════════════════════════════════════════
-- WHAT THIS MIGRATION DELIBERATELY DOES NOT DO
--
-- · Does not embed `student_answer`, `expected_answer`, or `marker_note`.
--   H.3: "not over answers or evidence content ... a similarity surface with
--   no academic query behind it and a real privacy cost."
-- · Does not backfill `label_embedding` or `declared_text_embedding`. That
--   backfill calls an embedding model, which is an M23-follow-on job
--   (EXECUTION_PLAN, "jobs/cron additions ... additive; each lands with the
--   milestone that needs it") — not something a migration file can honestly
--   do, and this milestone does not apply migrations or call external models
--   from a job either. `lib/academic-memory/query-planner.ts` documents the
--   query this index serves once populated (`semanticConceptQuery`); it is
--   correct today and simply returns zero rows until the column is filled,
--   which is the honest state for an index with no data yet, not a defect.
-- · Does not touch `concept_resolution.ts`'s existing lexical/fuzzy resolver
--   (`resolveConceptText`, `SEMANTIC_THRESHOLD`). That resolver already
--   answers "which concept did the student mean" deterministically and
--   without a model; the planner uses it first and the FTS index here as the
--   second-line, broader-recall fallback.
-- ═══════════════════════════════════════════════════════════════════════════

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '035',
  '035_academic_memory_search.sql',
  '80f334487e9484b75ffcc5c910a2b8425e6d75926b5e3987ba71ba8c78c5aacc',
  'self'
);

-- What this part left behind, from the database rather than from a claim:
SELECT version, name, recorded_by FROM supabase_migrations.schema_migrations ORDER BY version;
