-- ═══════════════════════════════════════════════════════════════════════════
-- STUDYLEDGER — PENDING MIGRATIONS, PART 1 OF 8
--
-- 008, 009, 010, 011, 012, 013
--
-- RUN THE PARTS IN ORDER. Each part is a whole number of migrations and is
-- idempotent, so a part that is interrupted can simply be run again.
--
-- Supabase → SQL Editor → New query. Press Ctrl+A then Delete FIRST: the
-- editor runs only the highlighted text if anything is selected, and a
-- partial run reports success.
--
-- GENERATED by scripts/build-pending.mjs. Do not edit by hand: fix the
-- migration in supabase/migrations and regenerate, or the paste and the
-- repo will disagree.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 008_ingestion.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 008_ingestion.sql — THE PIPELINE LEDGER
--
-- Additive. Touches nothing from 007_mistakes.sql: the mistake schema is
-- frozen, and this sits beside it rather than inside it.
--
-- Three tables, one job each:
--
--   ingestion_runs    one attempt to turn a paper into memory
--   ingestion_stages  APPEND-ONLY history of every stage attempt, forever
--   ingestion_review  what the pipeline refused to guess at
--
-- WHY THESE EXIST. The runner promises deterministic, resumable, idempotent,
-- observable, append-only, explainable execution. Every one of those is a
-- promise about STATE, and state has to live somewhere durable. Without this
-- ledger a crash at stage 7 means re-reading the paper from stage 1, and
-- "why did it say that?" has no answer.
--
-- Run in: Supabase → SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- INGESTION_RUNS — one pass over one paper
--
-- A replay is a NEW row pointing at the original through replay_of. History is
-- never overwritten, so a paper ingested today can be re-interpreted in 2030
-- against a better model, and both readings survive side by side.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS ingestion_runs (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- The paper. NULL only between run creation and intake completing.
  -- RESTRICT because evidence outlives everything built on it (§4.9).
  evidence_id  UUID REFERENCES evidence(id) ON DELETE RESTRICT,

  status       TEXT NOT NULL DEFAULT 'running' CHECK (
                 status IN ('running', 'awaiting-confirmation', 'awaiting-review',
                            'completed', 'failed')),

  -- THE CONFIRMATION GATE, persisted.
  -- Until this is set, no commit-phase stage may execute. The runner enforces
  -- it in code; this column is the durable record of WHEN the student decided.
  confirmed_at TIMESTAMPTZ,

  -- Points at the ORIGINAL run, not the immediate parent, so a chain of
  -- replays stays flat and every reading of one paper is trivially groupable.
  replay_of    UUID REFERENCES ingestion_runs(id) ON DELETE RESTRICT,

  -- Provenance: source filename, upload channel, client version.
  meta         JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- A replay must not claim to be its own original.
  CONSTRAINT ingestion_runs_replay_not_self CHECK (replay_of IS NULL OR replay_of <> id)
);

CREATE INDEX IF NOT EXISTS ingestion_runs_student_idx  ON ingestion_runs (student_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ingestion_runs_evidence_idx ON ingestion_runs (evidence_id);
CREATE INDEX IF NOT EXISTS ingestion_runs_replay_idx   ON ingestion_runs (replay_of);
CREATE INDEX IF NOT EXISTS ingestion_runs_status_idx   ON ingestion_runs (status)
  WHERE status IN ('running', 'awaiting-confirmation', 'awaiting-review');


-- ═══════════════════════════════════════════════════════════════════════════
-- INGESTION_STAGES — append-only, one row per ATTEMPT
--
-- A retry appends attempt n+1; it never edits attempt n. The unique constraint
-- on (run, stage, attempt) is what makes that structural rather than a
-- convention the application has to remember.
--
-- `output` is stored verbatim. That is what makes replay free: resuming reads
-- the ledger instead of re-calling a model, and re-running an unchanged stage
-- costs nothing.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS ingestion_stages (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id         UUID NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,

  stage          TEXT NOT NULL CHECK (stage IN (
                   'intake', 'preprocess', 'vision-read', 'segment', 'annotations',
                   'answers', 'candidates', 'concept-match', 'propose',
                   'occurrences', 'pattern-merge', 'score', 'next-action')),

  attempt        INTEGER NOT NULL CHECK (attempt >= 1),

  -- Bumped when a stage's logic changes. Combined with input_hash it forms the
  -- memo key, so a version bump forces honest re-execution.
  version        TEXT NOT NULL,

  -- Identifies the input. Equal hash + equal version = reuse, do not re-run.
  input_hash     TEXT NOT NULL,

  status         TEXT NOT NULL CHECK (status IN ('succeeded', 'failed', 'review')),

  -- The stage's typed output, verbatim. NULL unless succeeded.
  output         JSONB,

  confidence     NUMERIC CHECK (confidence BETWEEN 0 AND 1),
  model          TEXT,

  started_at     TIMESTAMPTZ NOT NULL,
  completed_at   TIMESTAMPTZ NOT NULL,
  duration_ms    INTEGER NOT NULL CHECK (duration_ms >= 0),

  failure_reason TEXT,

  -- One row per attempt. Re-writing an attempt is impossible, not discouraged.
  CONSTRAINT ingestion_stages_attempt_unique UNIQUE (run_id, stage, attempt),

  -- Succeeded means output; not-succeeded means a reason. No silent nulls.
  CONSTRAINT ingestion_stages_outcome_shape CHECK (
    (status = 'succeeded' AND output IS NOT NULL AND failure_reason IS NULL)
    OR
    (status <> 'succeeded' AND failure_reason IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS ingestion_stages_run_idx ON ingestion_stages (run_id, stage, attempt DESC);

-- Resume asks exactly one question: "what succeeded most recently?"
CREATE INDEX IF NOT EXISTS ingestion_stages_success_idx
  ON ingestion_stages (run_id, stage, attempt DESC)
  WHERE status = 'succeeded';


-- ═══════════════════════════════════════════════════════════════════════════
-- INGESTION_REVIEW — what the pipeline refused to guess
--
-- Reaching this table is a SUCCESS, not a failure. A stage that declines below
-- the confidence floor has done its job: PRODUCT_PRINCIPLES §3.2 forbids
-- storing a claim, and law 7 forbids inventing one.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS ingestion_review (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id     UUID NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,
  stage      TEXT NOT NULL,

  -- What could not be decided, and every option considered, with rationale.
  -- The student is shown the alternatives, never a silent best guess.
  items      JSONB NOT NULL,

  resolved_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ingestion_review_open_idx
  ON ingestion_review (run_id) WHERE resolved_at IS NULL;


-- ═══════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
--
-- A student may SEE everything the pipeline did with their paper — that is the
-- explainability guarantee, and it would be hollow if the history were hidden.
--
-- They may write nothing. The pipeline runs as the service role. The single
-- exception is confirmation, which is the student's decision to make and
-- theirs alone; it is granted through a narrow UPDATE policy below.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE ingestion_runs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingestion_review ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ingestion_runs_select_own ON ingestion_runs;
CREATE POLICY ingestion_runs_select_own ON ingestion_runs
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

-- The student confirms. Nothing else about a run is theirs to change, and the
-- WITH CHECK makes status the only other field they can move — never backwards
-- into a state that would re-open the gate.
DROP POLICY IF EXISTS ingestion_runs_confirm_own ON ingestion_runs;
CREATE POLICY ingestion_runs_confirm_own ON ingestion_runs
  FOR UPDATE TO authenticated
  USING (auth.uid() = student_id AND confirmed_at IS NULL)
  WITH CHECK (auth.uid() = student_id AND confirmed_at IS NOT NULL);

DROP POLICY IF EXISTS ingestion_stages_select_own ON ingestion_stages;
CREATE POLICY ingestion_stages_select_own ON ingestion_stages
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM ingestion_runs r WHERE r.id = run_id AND r.student_id = auth.uid())
  );

-- No INSERT, UPDATE or DELETE policy on ingestion_stages, for anyone.
-- The history is written by the service role and is append-only by construction.

DROP POLICY IF EXISTS ingestion_review_select_own ON ingestion_review;
CREATE POLICY ingestion_review_select_own ON ingestion_review
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM ingestion_runs r WHERE r.id = run_id AND r.student_id = auth.uid())
  );

-- ─── 009_migration_ledger.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 009_migration_ledger.sql   ·   M1-1
--
-- WHY THIS EXISTS
--
-- Architecture T1: "An append-only event store cannot tolerate schema drift —
-- a missing column silently loses data permanently." Finding A.5.a records the
-- current position exactly: `004_missing_tables.sql`'s own header states that
-- five tables the running code required were ABSENT from production on
-- 2026-07-12, and whether 004–008 have since been applied is UNVERIFIABLE from
-- the repository. There is no ledger, no runner, and CLAUDE.md tells the agent
-- to paste SQL into chat for hand-execution.
--
-- This migration makes the deployed schema KNOWABLE. After it runs, the
-- question "which repository migrations are applied to this database?" is a
-- query, not a guess — which is M1-1's done-when.
--
--
-- WHY NOT SUPABASE'S OWN TRACKING
--
-- Supabase DOES ship migration tracking natively: the CLI writes one row per
-- applied migration into `supabase_migrations.schema_migrations`
-- (version text PK, statements text[], name text). It was therefore checked
-- FIRST, and rejected as a complete answer for two repository facts:
--
--   1. Only the CLI writes that table. This repo has no `supabase/config.toml`,
--      no `supabase` dependency in package.json, and no CLI invocation
--      anywhere; every migration to date was pasted into the Supabase SQL
--      editor by hand. Hand-application writes nothing, so the native table is
--      empty or absent and records none of 000–008.
--   2. The native row carries no checksum. It answers "was a version applied",
--      never "was the file edited after it was applied" — and an edited applied
--      migration is the second half of drift, the half that makes two databases
--      claiming the same version actually differ.
--
-- So this migration does NOT build a parallel table. It ADOPTS the Supabase
-- table — same schema, same name, same primary key — and extends it additively
-- with the two columns the checksum gate needs. Adopting rather than
-- duplicating means the day this repo starts running `supabase db push`, the
-- CLI finds its own table already populated and keeps writing to it; a second
-- table would have created exactly the two-sources-of-truth problem H.1.a
-- forbids.
--
--
-- WHY THE BACKFILL PROBES INSTEAD OF ASSERTING
--
-- Backfilling 000–008 as "applied" because the files exist would restate the
-- guess this migration is meant to abolish. Each backfill row below is instead
-- guarded by a catalogue probe for the objects that migration creates, so a
-- row appears ONLY where the database itself is the evidence. A migration
-- whose objects are missing stays out of the ledger and the CI gate reports it
-- UNAPPLIED — which is the correct, loud outcome.
--
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. The ledger ──────────────────────────────────────────────────────────
-- Created with the Supabase CLI's exact shape so the CLI can later adopt it.
CREATE SCHEMA IF NOT EXISTS supabase_migrations;

CREATE TABLE IF NOT EXISTS supabase_migrations.schema_migrations (
  version     TEXT PRIMARY KEY,
  statements  TEXT[],
  name        TEXT
);

-- Additive extension. `ADD COLUMN IF NOT EXISTS` so this is a no-op on a
-- database where the CLI already created the table.
ALTER TABLE supabase_migrations.schema_migrations
  ADD COLUMN IF NOT EXISTS checksum    TEXT,
  ADD COLUMN IF NOT EXISTS applied_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS recorded_by TEXT;

COMMENT ON COLUMN supabase_migrations.schema_migrations.checksum IS
  'sha256 of the migration body (contents before the LEDGER REGISTRATION sentinel, CRLF-normalised, trailing whitespace trimmed). NULL means the row was backfilled from catalogue evidence and the exact text that ran is unknown.';
COMMENT ON COLUMN supabase_migrations.schema_migrations.recorded_by IS
  'How the row got here: "self" (the migration registered itself), "backfill:009" (catalogue-probe evidence), or "cli" (supabase db push).';

-- ── 2. Reading the ledger from CI ──────────────────────────────────────────
-- PostgREST exposes `public` only, and the ledger deliberately lives in
-- `supabase_migrations` where no student role can reach it. This function is
-- the one window onto it: service-role only, read-only, no arguments.
CREATE OR REPLACE FUNCTION public.migration_ledger()
RETURNS TABLE (version TEXT, name TEXT, checksum TEXT, applied_at TIMESTAMPTZ, recorded_by TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = supabase_migrations, public, pg_temp
AS $$
  SELECT m.version, m.name, m.checksum, m.applied_at, m.recorded_by
  FROM supabase_migrations.schema_migrations m
  ORDER BY m.version;
$$;

REVOKE ALL     ON FUNCTION public.migration_ledger() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.migration_ledger() FROM anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.migration_ledger() TO service_role;

-- ── 3. Recording helper ────────────────────────────────────────────────────
-- Every future migration ends with one call to this. Idempotent on re-run of
-- the same file; a DIFFERENT checksum for an already-recorded version is a
-- hard error rather than an overwrite, because silently accepting it would
-- destroy the only evidence that the file changed after it was applied.
CREATE OR REPLACE FUNCTION supabase_migrations.record_migration(
  p_version  TEXT,
  p_name     TEXT,
  p_checksum TEXT,
  p_source   TEXT DEFAULT 'self'
) RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  existing TEXT;
BEGIN
  SELECT checksum INTO existing
  FROM supabase_migrations.schema_migrations
  WHERE version = p_version;

  IF NOT FOUND THEN
    INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
    VALUES (p_version, p_name, p_checksum, p_source);
    RETURN;
  END IF;

  IF existing IS NULL THEN
    -- Upgrading a catalogue-probe backfill to a checksummed row.
    UPDATE supabase_migrations.schema_migrations
    SET checksum = p_checksum, name = p_name, recorded_by = p_source
    WHERE version = p_version;
    RETURN;
  END IF;

  IF existing IS DISTINCT FROM p_checksum THEN
    RAISE EXCEPTION
      'migration % is already recorded with checksum %, refusing to overwrite with % — the file was edited after it was applied; write a new migration instead',
      p_version, existing, p_checksum;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION supabase_migrations.record_migration(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;

-- ── 4. Evidence-based backfill of 000–008 ──────────────────────────────────
-- Checksums are of the files as they stand in the repository at 2026-08-14.
-- They are recorded so that any LATER edit to one of these files is caught as
-- DIVERGENT — not as a claim that this exact text is what originally ran.
-- Rows appear only where the objects exist. ON CONFLICT DO NOTHING so a
-- re-run, or a database the CLI already recorded, is never clobbered.

-- 000 — user_data, rooms, ai_history, error_logs, announcements
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '000', '000_initial_schema.sql',
       '25da5fcd5992aae5567ae1de6f5bc49c24ea45bf15652ee1d916304e8e793603', 'backfill:009'
WHERE to_regclass('public.user_data')     IS NOT NULL
  AND to_regclass('public.rooms')         IS NOT NULL
  AND to_regclass('public.ai_history')    IS NOT NULL
  AND to_regclass('public.error_logs')    IS NOT NULL
  AND to_regclass('public.announcements') IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 001 — ai_rate_limits
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '001', '001_rls.sql',
       '07caa3bdcc105bd833cc76d0275258523c8486447e2df03e090f95aa4bb29267', 'backfill:009'
WHERE to_regclass('public.ai_rate_limits') IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 002 — user_data.blob, rooms.bailed, rooms.session_end, user_data.updated_at
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '002', '002_blob_and_rooms.sql',
       '9b9fefb44bb1b04ec880131b0d13ac76ad9331ccb66a456c3592220ee0220026', 'backfill:009'
WHERE EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='user_data' AND column_name='blob')
  AND EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='rooms' AND column_name='bailed')
  AND EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='rooms' AND column_name='session_end')
  AND EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='user_data' AND column_name='updated_at')
ON CONFLICT (version) DO NOTHING;

-- 003 — user_data.ai_calls_today / ai_calls_reset_at
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '003', '003_ai_rate_limits.sql',
       '27c14a9b49173c42eec024d48156312146172467ee34666d1f9175ee098b1148', 'backfill:009'
WHERE EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='user_data' AND column_name='ai_calls_today')
  AND EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema='public' AND table_name='user_data' AND column_name='ai_calls_reset_at')
ON CONFLICT (version) DO NOTHING;

-- 004 — the drift of record. ALL FIVE tables must exist; four out of five is
-- not "applied", it is a partially-run paste, and the gate must say so.
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '004', '004_missing_tables.sql',
       '48efd712387f5e4ca14522507f912cef5835066b8e3d7aaa461cc0a5cb4a6198', 'backfill:009'
WHERE to_regclass('public.page_events')        IS NOT NULL
  AND to_regclass('public.jobs')               IS NOT NULL
  AND to_regclass('public.push_subscriptions') IS NOT NULL
  AND to_regclass('public.stripe_customers')   IS NOT NULL
  AND to_regclass('public.stripe_events')      IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 004b — the Stripe subset of 004
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '004b', '004b_stripe_tables_only.sql',
       'bfb7c3c3ab8859dc6d6d9cd42b96ddb7b1dc05ae931f4ad9ab4ad123644aaa56', 'backfill:009'
WHERE to_regclass('public.stripe_customers') IS NOT NULL
  AND to_regclass('public.stripe_events')    IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 005 — score_history
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '005', '005_score_history.sql',
       '91b1e9181f81b048be36e39b06b111517917a077a17c4ea2558a46222dd05719', 'backfill:009'
WHERE to_regclass('public.score_history') IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 006 — the consume_ai_call() RPC
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '006', '006_ai_usage_server_side.sql',
       'e28e08def22f9d806d18c11634674f9d710effa1f5936a8304b279be0f805e74', 'backfill:009'
WHERE EXISTS (SELECT 1 FROM pg_proc p
              JOIN pg_namespace n ON n.oid = p.pronamespace
              WHERE n.nspname = 'public' AND p.proname = 'consume_ai_call')
ON CONFLICT (version) DO NOTHING;

-- 007 — the mistake domain
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '007', '007_mistakes.sql',
       '46ae6e0b862a85c330f7cd7e448e0ca89603eb968d42fa844931f6ac4e40162a', 'backfill:009'
WHERE to_regclass('public.concepts')    IS NOT NULL
  AND to_regclass('public.evidence')    IS NOT NULL
  AND to_regclass('public.patterns')    IS NOT NULL
  AND to_regclass('public.occurrences') IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- 008 — ingestion
INSERT INTO supabase_migrations.schema_migrations (version, name, checksum, recorded_by)
SELECT '008', '008_ingestion.sql',
       '90bd3d46efe8d2236885e097731d23130ba7e5c166537093e9c41e583b88f0ca', 'backfill:009'
WHERE to_regclass('public.ingestion_runs')   IS NOT NULL
  AND to_regclass('public.ingestion_stages') IS NOT NULL
  AND to_regclass('public.ingestion_review') IS NOT NULL
ON CONFLICT (version) DO NOTHING;

-- ── 5. The reading this migration takes of the live database ───────────────
-- Not an assertion — a recorded observation, so the first run of this file
-- leaves behind the evidence that answers Finding A.5.a's "UNVERIFIABLE".
DO $$
DECLARE
  recorded INT;
  missing  TEXT;
BEGIN
  SELECT count(*) INTO recorded FROM supabase_migrations.schema_migrations;

  SELECT string_agg(v, ', ' ORDER BY v) INTO missing
  FROM (VALUES ('000'),('001'),('002'),('003'),('004'),('004b'),('005'),('006'),('007'),('008')) AS t(v)
  WHERE NOT EXISTS (SELECT 1 FROM supabase_migrations.schema_migrations m WHERE m.version = t.v);

  RAISE NOTICE 'migration ledger: % of 10 pre-ledger migrations evidenced as applied', recorded;
  IF missing IS NOT NULL THEN
    RAISE WARNING 'NOT EVIDENCED AS APPLIED (objects absent from this database): % — these will fail the CI gate as UNAPPLIED until they are run', missing;
  END IF;
END $$;

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '009',
  '009_migration_ledger.sql',
  '353e01740c425da9283ea19b2d81bf43b38095d18f9df1ee897f8b45e44845a0',
  'self'
);

-- ─── 010_score_history_active.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 010_score_history_active.sql   ·   M1-3
--
-- WHAT THIS RECONCILES
--
-- `app/api/cron/score-snapshot/route.ts` has written `score_history.active`
-- since the Integrity Sprint. **No migration in this repository ever created
-- that column.** 005 defines score_history without it and nothing after 005
-- alters the table; the column was introduced by an ALTER TABLE pasted into
-- the SQL editor and never written down. The route's own comment says so:
-- "The `active` column hasn't been added yet (hand-run migration)."
--
-- So the drift Finding A.5.a describes is worse than 004's: with 004, the repo
-- at least held the SQL and the doubt was whether it had been run. With
-- `score_history.active` the repo did not describe the deployed schema AT ALL,
-- and the only record that the column should exist was a runtime `catch`
-- branch in application code. That is T1 in its purest form — production
-- schema known only to whoever last used the SQL editor.
--
-- This migration writes the column down. `ADD COLUMN IF NOT EXISTS` makes it
-- correct in both worlds: a no-op where the hand-run ALTER already landed, the
-- fix where it did not.
--
--
-- WHY THE RUNTIME FALLBACK STAYS FOR NOW
--
-- M1-3's done-when is that the fallback at score-snapshot/route.ts:97-107 is
-- deleted "because it can no longer be needed". Writing this file does not
-- reach that state — it makes it reachable. The fallback may be deleted only
-- once the ledger shows version 010 recorded against production, which is a
-- query a human must run after applying this file. Deleting it before then
-- would trade a tolerated missing column for a hard 500 on the daily close,
-- and the close is the only writer of the score series. The exact verification
-- step is written into the route's comment.
--
--
-- DEFAULT SEMANTICS
--
-- DEFAULT FALSE, NOT NULL. `active` means "this user's blob showed corroborated
-- evidence of a qualifying academic event on this day" (`lib/active-close.ts`).
-- Rows written before the column existed have no such evidence recorded, and
-- backfilling them TRUE would fabricate activity — PRINCIPLES §7, "never lie".
-- FALSE is the honest reading of "we did not observe corroboration".
--
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE score_history
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN score_history.active IS
  'Corroborated academic activity on captured_on, per lib/active-close.ts. FALSE for rows written before the column existed — absence of evidence, never a claim of inactivity.';

-- ── Verification the founder can run after applying this file ──────────────
-- Confirms the column is really there before anyone deletes the runtime
-- fallback in app/api/cron/score-snapshot/route.ts.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'score_history'
      AND column_name  = 'active'
  ) THEN
    RAISE EXCEPTION 'score_history.active still absent after ALTER — do not remove the runtime fallback';
  END IF;
  RAISE NOTICE 'score_history.active present. The score-snapshot missing-column fallback is now removable; see the M1-3 note in that route.';
END $$;

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '010',
  '010_score_history_active.sql',
  'cc8a5f5986a3defb2801f73cfd818ca3f07a463ea8af5be5d156f97c0ba64d74',
  'self'
);

-- ─── 011_service_state.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 011_service_state.sql   ·   M4-3
--
-- WHAT THIS CLOSES
--
-- Architecture R.2, Finding A.5.e, stated exactly: `user_data.notifState` and
-- `user_data.parentAlerts` are documented "service-role writes only"
-- (`lib/user-data.ts:39-42`) and yet live in a row carrying a full
-- `user_data_update_own` UPDATE policy (`000_initial_schema.sql:142`).
--
-- The consequence is not theoretical. Both columns hold DEDUPLICATION state —
-- `notifState.sent` is the map of "we have already sent this nudge",
-- `parentAlerts.examAlerts` is the map of "we have already emailed this
-- parent about this paper". A student with devtools open can clear either one
-- with a single PostgREST call against their own row, and the system will
-- re-fire everything it had already suppressed. Clearing `notifState.sent`
-- reopens the whole push backlog; clearing `examAlerts` makes the exam-risk
-- alert to a PARENT fire again. Neither is data the student owns; both are
-- records the system keeps ABOUT the student, and R.2's rule is that
-- system-owned fields move out of student-writable rows.
--
-- This migration creates the two service-role tables that hold them, copies
-- whatever the columns currently contain, and leaves the columns in place.
--
--
-- WHY THE OLD COLUMNS ARE NOT DROPPED HERE
--
-- Additive only, deliberately, for two independent reasons:
--
--   1. **The columns are drift, and their presence is unproven.** `notifState`,
--      `parentAlerts`, `parentEmail` and `parentDigestEnabled` appear in NO
--      migration in this repository — not 000, not 004, not anywhere. Like
--      `score_history.active` before 010, they were introduced by an ALTER
--      pasted into the SQL editor and never written down (Finding A.5.a, T1).
--      A `DROP COLUMN` cannot be written against a shape the repository has
--      never described, and dropping in the same transaction that copies would
--      make the copy unverifiable.
--   2. **A one-way door.** Once the columns are gone the read path has no
--      fallback, so the drop belongs to a later, separate migration run only
--      after the ledger shows 011 recorded AND the copy below has been
--      inspected. The drop statements are written out at the foot of this file,
--      commented, so the follow-up is a paste rather than a rewrite.
--
-- Until that drop runs, the columns remain student-writable and a determined
-- student can still clear them — but nothing READS them any more (the cron
-- routes read and write the new tables as of this milestone), so clearing them
-- has no effect. The exposure closes with the code change; the drop is hygiene.
--
--
-- POSTURE: RLS ON, ZERO POLICIES
--
-- Both tables enable RLS and define no policy whatsoever. Under Postgres RLS
-- that denies every non-service-role read and write by construction — the
-- posture `jobs` already uses (architecture R.2: "`jobs` RLS-on with no
-- policies (service role only)"), chosen over a policy list because there is no
-- circumstance in which a student role should touch either table, and an empty
-- policy set cannot be loosened by accident the way an over-broad USING clause
-- can. Grants are revoked from `anon` and `authenticated` as well, so the
-- tables are unreachable even if RLS were ever disabled on them.
--
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- NOT APPLIED to any database by the milestone that wrote it.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Push notification engine state ──────────────────────────────────────
-- Mirrors `NotifState` in `lib/notifications.ts` field for field. `sent` stays
-- JSONB rather than becoming a child table: it is a bounded map (the engine
-- prunes it to the last 100 keys at `lib/notifications.ts:218`) that is read
-- and rewritten whole on every decision, and normalising it would buy nothing
-- and cost a join in an hourly cron loop.
CREATE TABLE IF NOT EXISTS notification_state (
  user_id                UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  sent                   JSONB       NOT NULL DEFAULT '{}'::jsonb,
  last_high_priority_day TEXT,
  last_milestone         INT,
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE notification_state IS
  'Service-role-only push dedup state (M4-3, architecture R.2). Formerly user_data.notifState, where the student could clear it. Never student-readable or student-writable.';
COMMENT ON COLUMN notification_state.sent IS
  'notification key -> ISO timestamp of the send. Pruned to the most recent 100 by lib/notifications.ts.';
COMMENT ON COLUMN notification_state.last_high_priority_day IS
  'Local YYYY-MM-DD on which the one daily high-priority slot was used.';

-- ── 2. Parent alert cooldowns ──────────────────────────────────────────────
-- `parentAlerts` also carried an `inactivityAt` marker. It is NOT recreated:
-- M0-4 removed the inactivity alert entirely, `computeRiskFlags` can only raise
-- `examSoon` (`lib/parent-digest.ts`), and no code has written `inactivityAt`
-- since. Carrying the column forward would re-establish a field for a signal
-- the product has ruled out escalating to a parent.
CREATE TABLE IF NOT EXISTS parent_alert_state (
  user_id     UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  exam_alerts JSONB       NOT NULL DEFAULT '{}'::jsonb,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE parent_alert_state IS
  'Service-role-only parent-alert cooldown markers (M4-3, architecture R.2). Formerly user_data.parentAlerts. A student clearing this could re-fire an email to their parent, which is why it moved.';
COMMENT ON COLUMN parent_alert_state.exam_alerts IS
  '"<exam name>@<exam date>" -> ISO timestamp of the alert already sent. One alert per exam occurrence.';

-- ── 3. RLS: on, with no policies at all ────────────────────────────────────
ALTER TABLE notification_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE parent_alert_state ENABLE ROW LEVEL SECURITY;

-- Belt as well as braces: revoke the table grants PostgREST's roles inherit, so
-- these tables are unreachable from the student API even if RLS were disabled.
REVOKE ALL ON TABLE notification_state FROM anon, authenticated;
REVOKE ALL ON TABLE parent_alert_state FROM anon, authenticated;
GRANT  ALL ON TABLE notification_state TO service_role;
GRANT  ALL ON TABLE parent_alert_state TO service_role;

-- ── 4. Copy whatever the drifted columns currently hold ────────────────────
-- Guarded by catalogue probes because, per the header, this repository has
-- never described these columns and cannot assume they exist. Where a column is
-- absent the copy is skipped and the new table simply starts empty, which is
-- the correct outcome: an absent column held no state to preserve.
--
-- `ON CONFLICT DO NOTHING` makes a re-run a no-op rather than a rollback of
-- state the cron has written since the first run.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'user_data' AND column_name = 'notifState'
  ) THEN
    EXECUTE $copy$
      INSERT INTO notification_state (user_id, sent, last_high_priority_day, last_milestone)
      SELECT u.id::uuid,
             COALESCE(u."notifState" -> 'sent', '{}'::jsonb),
             u."notifState" ->> 'lastHighPriorityDay',
             NULLIF(u."notifState" ->> 'lastMilestone', '')::int
      FROM user_data u
      WHERE u."notifState" IS NOT NULL
        AND jsonb_typeof(u."notifState") = 'object'
      ON CONFLICT (user_id) DO NOTHING
    $copy$;
    RAISE NOTICE 'notification_state: copied from user_data."notifState"';
  ELSE
    RAISE NOTICE 'notification_state: user_data."notifState" absent — nothing to copy, table starts empty';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'user_data' AND column_name = 'parentAlerts'
  ) THEN
    EXECUTE $copy$
      INSERT INTO parent_alert_state (user_id, exam_alerts)
      SELECT u.id::uuid, COALESCE(u."parentAlerts" -> 'examAlerts', '{}'::jsonb)
      FROM user_data u
      WHERE u."parentAlerts" IS NOT NULL
        AND jsonb_typeof(u."parentAlerts") = 'object'
      ON CONFLICT (user_id) DO NOTHING
    $copy$;
    RAISE NOTICE 'parent_alert_state: copied from user_data."parentAlerts"';
  ELSE
    RAISE NOTICE 'parent_alert_state: user_data."parentAlerts" absent — nothing to copy, table starts empty';
  END IF;
END $$;

-- ── 5. Verification the founder can run after applying this file ───────────
DO $$
DECLARE
  n_pol INT;
  p_pol INT;
BEGIN
  SELECT count(*) INTO n_pol FROM pg_policies WHERE schemaname='public' AND tablename='notification_state';
  SELECT count(*) INTO p_pol FROM pg_policies WHERE schemaname='public' AND tablename='parent_alert_state';

  IF n_pol <> 0 OR p_pol <> 0 THEN
    RAISE EXCEPTION
      'service-state tables must carry ZERO RLS policies (found % and %) — a policy here would re-expose system state to the student role',
      n_pol, p_pol;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
                 WHERE n.nspname='public' AND c.relname='notification_state' AND c.relrowsecurity)
     OR NOT EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
                 WHERE n.nspname='public' AND c.relname='parent_alert_state' AND c.relrowsecurity) THEN
    RAISE EXCEPTION 'RLS is not enabled on both service-state tables';
  END IF;

  RAISE NOTICE 'M4-3: notification_state and parent_alert_state present, RLS on, no policies. Service role only.';
END $$;

-- ── 6. THE FOLLOW-UP DROP — do not run with this file ──────────────────────
-- Run only after (a) the ledger records version 011 against this database, and
-- (b) the copied rows have been eyeballed against the old columns. Written here
-- so the follow-up migration is a paste, not a rewrite.
--
--   ALTER TABLE user_data DROP COLUMN IF EXISTS "notifState";
--   ALTER TABLE user_data DROP COLUMN IF EXISTS "parentAlerts";

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '011',
  '011_service_state.sql',
  '93b4fe36c9eea7830615b87c5947788aec4cb3f0fc2f186f8e6287d6229acb50',
  'self'
);

-- ─── 012_students_and_profiles.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 012_students_and_profiles.sql   ·   M5-1
--
-- WHAT THIS CLOSES
--
-- Architecture C.2 (`Student`) and C.3 (`StudentProfile`), and S.1's row
-- *"`user_data` flat columns — ADAPT — profile columns migrate to versioned
-- `student_profiles`"*. The CURRENT FACT recorded at C.3 is exact:
--
--   > Profile lives in 18 flat `user_data` columns *and* in
--   > `localStorage["ledger-profile"]`, and `lib/user-data.ts:123` returns
--   > `{ ...(data as UserData), ...localProfile }` — **localStorage wins over
--   > Postgres.**
--
-- This migration builds the two tables that end that arrangement:
--
--   `students`          — the durable identity anchor. One row per
--                         `auth.users` row. Nothing about the student, only
--                         that the student exists.
--   `student_profiles`  — what the student has DECLARED about themselves,
--                         as an append-only version chain rather than a row
--                         that gets overwritten.
--
--
-- WHY THE PROFILE IS VERSIONED, IN ONE SENTENCE FROM C.3
--
--   > A board change retroactively reinterprets every prior event. Without a
--   > version chain, a student who switches CBSE→IB in Grade 11 silently
--   > rewrites the meaning of their Grade 10 record.
--
-- So there is no UPDATE path on a profile. A change is a new row at
-- `version + 1`, carrying `effective_from`, `changed_by` and `change_reason`,
-- and the previous row keeps its values forever with `is_current = FALSE`.
-- The identity of a version is `(student_id, version)`, exactly as C.3
-- specifies, and "which one is live" is a partial unique index — not a
-- convention, not application discipline, an index the database enforces.
--
--
-- WHY THERE IS NO INSERT OR UPDATE POLICY, AND WHAT REPLACES IT
--
-- This is the data-integrity half of M5-2 and the reason it lives in SQL
-- rather than in TypeScript.
--
-- Today `lib/user-data.ts:149-152` changes one profile field by loading the
-- whole row, spreading it, and upserting the result. Between the read and the
-- write, any other tab, device or cron write to a DIFFERENT field of the same
-- row is silently reverted — last writer wins, and the loser is never told.
-- Relocating that pattern onto a new table would have changed nothing.
--
-- So `student_profiles` grants the student SELECT and nothing else. There is
-- no INSERT policy, no UPDATE policy, no DELETE policy: under Postgres RLS
-- that denies each of those by construction. The one write path is
-- `public.set_student_profile()` below — `SECURITY DEFINER`, so it can write
-- past those policies, and it:
--
--   1. resolves the writer from `auth.uid()`, never from an argument, so a
--      caller cannot name someone else's `student_id`;
--   2. takes `FOR UPDATE` on the caller's `students` row first, so two
--      concurrent calls SERIALISE instead of racing;
--   3. reads the current version and appends `version + 1` inside that same
--      transaction, so the version chain is gapless and no field carried
--      forward can be a stale value read before someone else's write.
--
-- A NULL argument means "carry this field forward from the current version"
-- and never "set this field to NULL". Explicit clearing is `p_clear`, a list
-- of field names — because "unset" and "unchanged" must be distinguishable,
-- and a merge that cannot tell them apart is how the old code lost data.
--
-- The result is that a partial profile write is one statement in one
-- transaction under one lock. There is no window between the read and the
-- write in which anything can be lost.
--
--
-- ADDITIVE ONLY — THE `user_data` COLUMNS ARE NOT DROPPED HERE
--
-- Same reasoning as `011_service_state.sql`, and the same shape of follow-up:
-- this file is written to be applied to a database that is still serving the
-- old read path, so the old columns must keep working until the new path is
-- deployed and confirmed. The drop statements are written out, commented, at
-- the foot of this file. Section 6 backfills the existing flat columns into
-- version 1 of each student's chain, so nothing is stranded.
--
-- Run in: Supabase → SQL Editor. Idempotent; safe to re-run.
-- NOT APPLIED to any database by the milestone that wrote it.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. `students` — the identity anchor (architecture C.2) ─────────────────
-- Deliberately almost empty. C.2: "Key fields: `created_at`, `deleted_at
-- NULL`, `data_region`" and "partition key of every other student-scoped
-- table". Everything a student can CHANGE about themselves lives in the
-- profile chain, not here, so that this row can be the stable thing every
-- future foreign key points at.
--
-- Entitlement is NOT here, and must never be added: C.2 records as a CURRENT
-- FACT to keep verbatim that tier lives in `auth.users.app_metadata.tier`
-- (`lib/tier.ts:30-36`), deliberately outside the student-writable row.
CREATE TABLE IF NOT EXISTS students (
  student_id  UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,
  data_region TEXT        NOT NULL DEFAULT 'in'
);

COMMENT ON TABLE students IS
  'The durable identity anchor (M5-1, architecture C.2). One row per auth.users row, created on first sign-in via public.ensure_student(). Deletion is a tombstone in deleted_at plus cascade (Part O.5), never an in-place edit.';
COMMENT ON COLUMN students.deleted_at IS
  'Soft-delete tombstone. A non-NULL value means the account is deleted; the row itself is never removed, so foreign keys from the academic record stay resolvable.';
COMMENT ON COLUMN students.data_region IS
  'Where this student''s data is held. Single-valued today; the column exists so a second region is a data change rather than a schema change.';

-- ── 2. `student_profiles` — the version chain (architecture C.3) ───────────
CREATE TABLE IF NOT EXISTS student_profiles (
  student_id     UUID        NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
  version        INT         NOT NULL CHECK (version > 0),

  -- Declared curriculum. All nullable: a profile that does not yet know the
  -- answer must be representable, because §2.6 ratifies asking two questions
  -- and the rest of these fields are therefore usually unknown at first write.
  board          TEXT,
  grade          TEXT,
  stream         TEXT,
  target_exam    TEXT,
  subjects       TEXT[],
  interests      TEXT[],

  -- Retained so the backfill in section 6 is lossless. `PRODUCT_DECISIONS`
  -- §2.6 does not ratify asking a student for a learning or communication
  -- style, so the rebuilt onboarding never writes this; it exists to carry
  -- forward what the retired eight-step flow already collected.
  ai_profile     JSONB,

  -- Provenance of THIS version.
  effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),
  changed_by     TEXT        NOT NULL DEFAULT 'student'
                 CHECK (changed_by IN ('student', 'system', 'backfill:012')),
  change_reason  TEXT,

  is_current     BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (student_id, version)
);

COMMENT ON TABLE student_profiles IS
  'Append-only profile version chain (M5-1, architecture C.3). A change is a new row at version+1, never an UPDATE: a board change retroactively reinterprets every prior event, so the value that was true at the time must remain readable. Written only through public.set_student_profile().';
COMMENT ON COLUMN student_profiles.subjects IS
  'The subjects the student declares they are studying. One of the two questions PRODUCT_DECISIONS §2.6 ratifies for onboarding.';
COMMENT ON COLUMN student_profiles.interests IS
  'Non-curricular interests, architecture C.3. Distinct from `subjects` and NOT asked at onboarding. Left NULL by the 012 backfill — see section 6.';
COMMENT ON COLUMN student_profiles.is_current IS
  'Exactly one TRUE row per student, enforced by the partial unique index below rather than by application discipline.';
COMMENT ON COLUMN student_profiles.changed_by IS
  'Who caused this version to exist. "backfill:012" marks a row derived from the pre-M5 user_data columns rather than from an act by the student.';

-- THE INVARIANT, AS AN INDEX. Two concurrent writers cannot both leave a
-- current row: the second one to commit violates this index and is rolled
-- back. This is the structural backstop behind the lock in
-- `set_student_profile()` — the lock makes the common case correct, the index
-- makes the impossible case impossible.
CREATE UNIQUE INDEX IF NOT EXISTS student_profiles_one_current
  ON student_profiles (student_id) WHERE is_current;

-- Reading a student's own history, newest first.
CREATE INDEX IF NOT EXISTS student_profiles_chain
  ON student_profiles (student_id, version DESC);

-- ── 3. RLS: read your own, write through the function or not at all ───────
ALTER TABLE students         ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS students_select_own ON students;
CREATE POLICY students_select_own ON students
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

-- No INSERT policy: rows are created by public.ensure_student().
-- No UPDATE policy: nothing on this row is student-editable.
-- No DELETE policy: deletion is a tombstone written by the service role
--   (architecture O.5), never a row disappearing under the academic record.

DROP POLICY IF EXISTS student_profiles_select_own ON student_profiles;
CREATE POLICY student_profiles_select_own ON student_profiles
  FOR SELECT TO authenticated USING (auth.uid() = student_id);

-- No INSERT policy. No UPDATE policy. No DELETE policy. See the header:
-- the single write path is public.set_student_profile(), and a student who
-- cannot UPDATE cannot rewrite what they declared last term.

-- ── 4. `ensure_student()` — idempotent identity creation ──────────────────
-- Called on first sign-in and again by `set_student_profile()`, so onboarding
-- is one round trip and a student whose row was never created (every account
-- that exists today) is repaired on their next write rather than erroring.
CREATE OR REPLACE FUNCTION public.ensure_student()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid UUID := auth.uid();
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'ensure_student: no authenticated caller'
      USING ERRCODE = '28000';
  END IF;

  INSERT INTO students (student_id) VALUES (v_uid)
  ON CONFLICT (student_id) DO NOTHING;

  RETURN v_uid;
END;
$$;

REVOKE ALL     ON FUNCTION public.ensure_student() FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.ensure_student() TO authenticated, service_role;

COMMENT ON FUNCTION public.ensure_student() IS
  'Creates the caller''s students row if absent and returns auth.uid(). SECURITY DEFINER because students carries no INSERT policy; the identity is taken from auth.uid() and never from an argument.';

-- ── 5. `set_student_profile()` — the ONLY profile write path ──────────────
-- This function is M5-2's done-when expressed in SQL: "no unguarded whole-row
-- read-modify-write remains". The read and the write are one transaction, the
-- caller's identity row is locked first so concurrent calls serialise, and a
-- field the caller did not mention is carried forward from the version that
-- is current AT THAT MOMENT — not from a value the client read seconds ago.
--
-- NULL argument  → carry the field forward unchanged.
-- Name in p_clear → set the field to NULL in the new version.
-- Both           → p_clear wins; it is the explicit instruction.
CREATE OR REPLACE FUNCTION public.set_student_profile(
  p_board         TEXT   DEFAULT NULL,
  p_grade         TEXT   DEFAULT NULL,
  p_stream        TEXT   DEFAULT NULL,
  p_target_exam   TEXT   DEFAULT NULL,
  p_subjects      TEXT[] DEFAULT NULL,
  p_interests     TEXT[] DEFAULT NULL,
  p_ai_profile    JSONB  DEFAULT NULL,
  p_change_reason TEXT   DEFAULT NULL,
  p_clear         TEXT[] DEFAULT '{}'
)
RETURNS student_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid  UUID := auth.uid();
  v_cur  student_profiles;
  v_new  student_profiles;
  v_lock UUID;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'set_student_profile: no authenticated caller'
      USING ERRCODE = '28000';
  END IF;

  PERFORM public.ensure_student();

  -- Serialise concurrent writers on the identity row. Everything below runs
  -- with this lock held, which is what makes the read-then-append safe.
  SELECT student_id INTO v_lock FROM students
   WHERE student_id = v_uid
     FOR UPDATE;

  SELECT * INTO v_cur FROM student_profiles
   WHERE student_id = v_uid AND is_current;

  -- Retire the outgoing version. Zero rows on the first write; exactly one
  -- thereafter, because of student_profiles_one_current.
  UPDATE student_profiles SET is_current = FALSE
   WHERE student_id = v_uid AND is_current;

  INSERT INTO student_profiles (
    student_id, version,
    board, grade, stream, target_exam, subjects, interests, ai_profile,
    effective_from, changed_by, change_reason, is_current
  ) VALUES (
    v_uid,
    COALESCE(v_cur.version, 0) + 1,
    CASE WHEN 'board'       = ANY(p_clear) THEN NULL ELSE COALESCE(p_board,       v_cur.board)       END,
    CASE WHEN 'grade'       = ANY(p_clear) THEN NULL ELSE COALESCE(p_grade,       v_cur.grade)       END,
    CASE WHEN 'stream'      = ANY(p_clear) THEN NULL ELSE COALESCE(p_stream,      v_cur.stream)      END,
    CASE WHEN 'target_exam' = ANY(p_clear) THEN NULL ELSE COALESCE(p_target_exam, v_cur.target_exam) END,
    CASE WHEN 'subjects'    = ANY(p_clear) THEN NULL ELSE COALESCE(p_subjects,    v_cur.subjects)    END,
    CASE WHEN 'interests'   = ANY(p_clear) THEN NULL ELSE COALESCE(p_interests,   v_cur.interests)   END,
    CASE WHEN 'ai_profile'  = ANY(p_clear) THEN NULL ELSE COALESCE(p_ai_profile,  v_cur.ai_profile)  END,
    now(), 'student', p_change_reason, TRUE
  )
  RETURNING * INTO v_new;

  RETURN v_new;
END;
$$;

REVOKE ALL     ON FUNCTION public.set_student_profile(TEXT, TEXT, TEXT, TEXT, TEXT[], TEXT[], JSONB, TEXT, TEXT[]) FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION public.set_student_profile(TEXT, TEXT, TEXT, TEXT, TEXT[], TEXT[], JSONB, TEXT, TEXT[]) TO authenticated, service_role;

COMMENT ON FUNCTION public.set_student_profile(TEXT, TEXT, TEXT, TEXT, TEXT[], TEXT[], JSONB, TEXT, TEXT[]) IS
  'The only write path for a student profile (M5-2). Appends version+1 under FOR UPDATE on the caller''s students row; NULL means carry forward, p_clear means set NULL. Replaces the whole-row read-modify-write at lib/user-data.ts:139-142.';

-- ── 6. Backfill: the flat `user_data` columns become version 1 ────────────
-- Guarded by a catalogue probe, for the reason 011 gives: several `user_data`
-- columns in this repository were introduced by hand-run ALTERs and the
-- repository cannot assume any particular shape (Finding A.5.a, T1).
--
-- `changed_by = 'backfill:012'` so a derived row is never mistaken for an act
-- by the student. `ON CONFLICT DO NOTHING` makes a re-run a no-op rather than
-- a second version-1 attempt.
--
-- ON THE INTEREST → SUBJECT MAPPING. The retired onboarding asked *"Which
-- subjects interest you? Pick at least 2"* and stored the answer in
-- `user_data.interests`. That answer is a subject declaration, and §2.6
-- ratifies subjects as one of the two onboarding questions, so it lands in
-- `subjects`. `student_profiles.interests` — non-curricular interests per C.3
-- — is left NULL, because nothing was ever collected for it and inventing a
-- value would be a §7 violation.
-- REWRITTEN 2026-08-30, after this block failed twice on production:
--   ERROR 42703: column u.created_at does not exist
--   ERROR 42883: operator does not exist: uuid = text
--
-- Two independent drifts, in one table. `user_data` predates the migration
-- ledger, so no migration owns its shape and nothing ever checked that two
-- databases agreed about it. They do not:
--
--   staging:    id UUID, created_at present, camelCase "targetExam"
--   production: id TEXT, no created_at,      snake_case target_exam
--
-- 006 already met the type half and documented the fix: cast, and guard
-- against an id that is not a well-formed UUID, because the cast would abort
-- the whole migration on one bad row. 011, 012 and 029 all read user_data and
-- none of them had adopted it. They do now.
--
-- The column half is met by asking information_schema and building the
-- statements from what is actually present. A column in neither database
-- contributes NULL, which is the honest value: nothing was collected, so
-- nothing is claimed. Deliberately NOT met by adding the missing columns to
-- production, which would be inventing history on a live table to make a
-- backfill convenient.
DO $$
DECLARE
  has_created_at  BOOLEAN;
  col_target_exam TEXT;
  expr_created    TEXT;
  expr_exam       TEXT;
  typ_interests   TEXT;
  typ_ai          TEXT;
  expr_interests  TEXT;
  expr_ai         TEXT;
  pred_interests  TEXT;
  pred_ai         TEXT;
  uuid_shape      TEXT := '________-____-____-____-____________';
BEGIN
  IF to_regclass('public.user_data') IS NULL THEN
    RAISE NOTICE '012 backfill: user_data absent, students and student_profiles start empty';
    RETURN;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'user_data' AND column_name = 'created_at'
  ) INTO has_created_at;

  SELECT column_name INTO col_target_exam
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'user_data'
    AND column_name IN ('targetExam', 'target_exam')
  ORDER BY (column_name = 'targetExam') DESC
  LIMIT 1;

  -- Types, not just names.
  --
  -- The first sweep asked which columns EXIST and stopped there, which is
  -- how this defect survived it: `interests` is text[] in production and
  -- jsonb in staging. jsonb_typeof() only accepts jsonb, so on production
  -- the statement failed to resolve at all.
  --
  -- A column that is absent, or of a type carrying no usable value,
  -- contributes NULL and a FALSE predicate: nothing was collected, so
  -- nothing is claimed.
  SELECT data_type INTO typ_interests
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'user_data'
    AND column_name = 'interests';

  SELECT data_type INTO typ_ai
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'user_data'
    AND column_name = 'aiProfile';

  -- interests -> TEXT[]
  IF typ_interests = 'ARRAY' THEN
    expr_interests := 'CASE WHEN COALESCE(array_length(u.interests, 1), 0) > 0 '
                   || 'THEN u.interests ELSE NULL END';
    pred_interests := 'COALESCE(array_length(u.interests, 1), 0) > 0';
  ELSIF typ_interests = 'jsonb' THEN
    expr_interests := 'CASE WHEN jsonb_typeof(u.interests) = ''array'' '
                   || '      AND jsonb_array_length(u.interests) > 0 '
                   || '     THEN ARRAY(SELECT jsonb_array_elements_text(u.interests)) ELSE NULL END';
    pred_interests := 'jsonb_typeof(u.interests) = ''array''';
  ELSIF typ_interests = 'json' THEN
    expr_interests := 'CASE WHEN jsonb_typeof(u.interests::jsonb) = ''array'' '
                   || '      AND jsonb_array_length(u.interests::jsonb) > 0 '
                   || '     THEN ARRAY(SELECT jsonb_array_elements_text(u.interests::jsonb)) ELSE NULL END';
    pred_interests := 'jsonb_typeof(u.interests::jsonb) = ''array''';
  ELSE
    expr_interests := 'NULL::text[]';
    pred_interests := 'FALSE';
  END IF;

  -- aiProfile -> JSONB
  IF typ_ai = 'jsonb' THEN
    expr_ai := 'CASE WHEN jsonb_typeof(u."aiProfile") = ''object'' THEN u."aiProfile" ELSE NULL END';
    pred_ai := 'jsonb_typeof(u."aiProfile") = ''object''';
  ELSIF typ_ai = 'json' THEN
    expr_ai := 'CASE WHEN jsonb_typeof(u."aiProfile"::jsonb) = ''object'' THEN u."aiProfile"::jsonb ELSE NULL END';
    pred_ai := 'jsonb_typeof(u."aiProfile"::jsonb) = ''object''';
  ELSIF typ_ai IN ('text', 'character varying') THEN
    -- text that may or may not hold JSON. A bad parse must not abort the
    -- migration, so check the cheap way before casting.
    expr_ai := 'CASE WHEN u."aiProfile" LIKE ''{%'' '
            || '      AND jsonb_typeof(u."aiProfile"::jsonb) = ''object'' '
            || '     THEN u."aiProfile"::jsonb ELSE NULL END';
    pred_ai := '(u."aiProfile" LIKE ''{%'')';
  ELSE
    expr_ai := 'NULL::jsonb';
    pred_ai := 'FALSE';
  END IF;

  expr_created := CASE WHEN has_created_at THEN 'u.created_at' ELSE 'NULL::timestamptz' END;
  expr_exam    := CASE WHEN col_target_exam IS NULL THEN 'NULL::text'
                       ELSE format('NULLIF(u.%I, %L)', col_target_exam, '') END;

  -- Identity first: a profile row has a foreign key to it.
  --
  -- The UUID guard is a LIKE pattern rather than a regex on purpose: a regex
  -- ending in the anchor character is read by format() as the start of a
  -- positional placeholder, and 36 single-character wildcards say the same
  -- thing without that hazard.
  EXECUTE format(
    'INSERT INTO students (student_id, created_at) '
    'SELECT u.id::uuid, COALESCE(%s, now()) FROM user_data u '
    'WHERE u.id IS NOT NULL AND u.id::text LIKE %L '
    '  AND EXISTS (SELECT 1 FROM auth.users a WHERE a.id::text = u.id::text) '
    'ON CONFLICT (student_id) DO NOTHING',
    expr_created, uuid_shape);

  EXECUTE format(
    'INSERT INTO student_profiles ('
    '  student_id, version, board, grade, stream, target_exam, subjects,'
    '  ai_profile, effective_from, changed_by, change_reason, is_current) '
    'SELECT u.id::uuid, 1, '
    '  NULLIF(u.board, %L), NULLIF(u.grade, %L), NULLIF(u.stream, %L), %s, '
    '  %s, '
    '  %s, '
    '  COALESCE(u.updated_at, %s, now()), '
    '  ''backfill:012'', ''flat user_data columns, migrated by 012'', TRUE '
    'FROM user_data u '
    'WHERE u.id IS NOT NULL AND u.id::text LIKE %L '
    '  AND EXISTS (SELECT 1 FROM students s WHERE s.student_id = u.id::uuid) '
    '  AND (NULLIF(u.board, %L) IS NOT NULL OR NULLIF(u.grade, %L) IS NOT NULL '
    '    OR NULLIF(u.stream, %L) IS NOT NULL OR %s IS NOT NULL '
    '    OR %s '
    '    OR %s) '
    'ON CONFLICT (student_id, version) DO NOTHING',
    '', '', '', expr_exam, expr_interests, expr_ai, expr_created, uuid_shape,
    '', '', '', expr_exam, pred_interests, pred_ai);

  RAISE NOTICE '012 backfill: students and version-1 profiles derived from user_data (created_at: %, target exam: %, interests: %, aiProfile: %)',
    has_created_at, COALESCE(col_target_exam, 'none'),
    COALESCE(typ_interests, 'absent'), COALESCE(typ_ai, 'absent');
END $$;

-- ── 7. Verification the founder can run after applying this file ──────────
DO $$
DECLARE
  n_write_pol INT;
  n_multi     INT;
BEGIN
  -- The write posture is the whole point. A student-facing INSERT or UPDATE
  -- policy on the profile chain would reopen the read-modify-write path.
  SELECT count(*) INTO n_write_pol
  FROM pg_policies
  WHERE schemaname = 'public'
    AND tablename IN ('students', 'student_profiles')
    AND cmd <> 'SELECT';

  IF n_write_pol <> 0 THEN
    RAISE EXCEPTION
      'students/student_profiles must carry SELECT policies only (found % write policies) — writes go through set_student_profile()',
      n_write_pol;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'student_profiles' AND c.relrowsecurity
  ) OR NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'students' AND c.relrowsecurity
  ) THEN
    RAISE EXCEPTION 'RLS is not enabled on both M5-1 tables';
  END IF;

  SELECT count(*) INTO n_multi FROM (
    SELECT student_id FROM student_profiles WHERE is_current
    GROUP BY student_id HAVING count(*) > 1
  ) x;

  IF n_multi <> 0 THEN
    RAISE EXCEPTION 'student_profiles: % students carry more than one current version', n_multi;
  END IF;

  RAISE NOTICE 'M5-1: students + student_profiles present, RLS on, SELECT-only policies, one current version per student.';
END $$;

-- ── 8. THE FOLLOW-UP DROP — do not run with this file ─────────────────────
-- Run only after (a) the ledger records version 012 against this database,
-- (b) the backfilled version-1 rows have been compared against the columns
-- they came from, and (c) the deployed build reads the profile through
-- `lib/student-context.ts` rather than through the flat columns. Written out
-- here so the follow-up migration is a paste, not a rewrite.
--
--   ALTER TABLE user_data DROP COLUMN IF EXISTS grade;
--   ALTER TABLE user_data DROP COLUMN IF EXISTS board;
--   ALTER TABLE user_data DROP COLUMN IF EXISTS stream;
--   ALTER TABLE user_data DROP COLUMN IF EXISTS interests;
--   ALTER TABLE user_data DROP COLUMN IF EXISTS "targetExam";
--   ALTER TABLE user_data DROP COLUMN IF EXISTS "aiProfile";
--   ALTER TABLE user_data DROP COLUMN IF EXISTS "onboardingDone";

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '012',
  '012_students_and_profiles.sql',
  'a8133d22fe77a37a253e0ebcaf25dc05334e8554b1b1b84946c20f5e1fa61bbc',
  'self'
);

-- ─── 013_concept_identity.sql ───

-- ═══════════════════════════════════════════════════════════════════════════
-- 013_concept_identity.sql — MERGES, TAXONOMY VERSION, ALIASES
--
-- EXECUTION_PLAN M6-2: *"Add `merged_into` and `taxonomy_version`. Done when:
-- concept merges are representable without rewriting history."*
-- EXECUTION_PLAN M6-3 needs somewhere for the ALIAS tier to read from.
--
-- ADDITIVE ONLY, and it does not touch `007_mistakes.sql`. Architecture C.2
-- classes `Concept` as **CURRENT FACT — exists**, and names exactly two new
-- columns as TARGET DESIGN. Editing 007 in place is the drift M1 exists to
-- prevent: the ledger records "this exact text was run", so a shipped migration
-- is never revised — it is extended by a later one.
--
--   1. concepts.merged_into      — a superseded concept POINTS at its
--                                  replacement instead of being deleted
--   2. concepts.taxonomy_version — which cut of the seeded tree a row came from
--   3. concept_aliases           — curated surface forms, the M6-3 alias tier
--
-- WHY A POINTER AND NOT A REWRITE. Occurrences, patterns and (from M7) every
-- academic event address concepts by id. If a merge deleted the loser and
-- repointed its references, the record would be rewritten retroactively —
-- PRINCIPLES §3.2, *"facts are immutable and never deleted; a correction
-- appends a superseding fact rather than editing history."* With a pointer, a
-- 2026 occurrence keeps pointing at the concept it was actually recorded
-- against, and resolution follows the pointer forward at read time. Nothing
-- about the past changes; only what the present calls it does.
--
-- Run in: Supabase → SQL Editor.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · MERGED_INTO — supersession without deletion (C.2)
--
-- ON DELETE RESTRICT matches the existing `parent_id` posture in 007: a concept
-- that anything points at cannot be removed. B.4: *"Concepts are never
-- hard-deleted … they are superseded, with a `merged_into` pointer so
-- historical references stay resolvable."*
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE concepts
  ADD COLUMN IF NOT EXISTS merged_into UUID REFERENCES concepts(id) ON DELETE RESTRICT;

-- A concept cannot supersede itself. Without this, one bad write makes the
-- merge chain an infinite loop for every reader, forever.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'concepts_merge_not_self'
  ) THEN
    ALTER TABLE concepts
      ADD CONSTRAINT concepts_merge_not_self
      CHECK (merged_into IS NULL OR merged_into <> id);
  END IF;
END $$;

-- Reverse lookup: "what was merged into this concept?" A merge is a curation
-- act that has to be reviewable, so the inverse must be cheap.
CREATE INDEX IF NOT EXISTS concepts_merged_into_idx
  ON concepts (merged_into) WHERE merged_into IS NOT NULL;


-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · TAXONOMY_VERSION — which cut of the tree this row came from (C.2)
--
-- *"`taxonomy_version INT` so a re-cut of the tree is detectable."*
--
-- DEFAULT 1 and NOT NULL: every row that already exists came from the first
-- cut, and there is no honest "unknown" value — the seed is deterministic
-- (UUIDv5 over a fixed namespace), so the rows that exist are exactly the rows
-- version 1 produces. A later re-cut writes 2 and the difference is a query,
-- not an archaeology exercise.
--
-- NOT a per-concept revision counter. It answers "which taxonomy cut", never
-- "how many times has this concept been edited" — that belongs to the curation
-- audit trail, which is M7's AuditEntry and not this table's job.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE concepts
  ADD COLUMN IF NOT EXISTS taxonomy_version INTEGER NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'concepts_taxonomy_version_positive'
  ) THEN
    ALTER TABLE concepts
      ADD CONSTRAINT concepts_taxonomy_version_positive
      CHECK (taxonomy_version >= 1);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS concepts_taxonomy_version_idx ON concepts (taxonomy_version);


-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · CONCEPT_ALIASES — the M6-3 alias tier (B.4, "hold aliases")
--
-- B.4 lists "hold aliases" as a responsibility of this subsystem and gives the
-- resolution order as exact → alias → semantic. Without a place to put them,
-- tier 2 has nothing to read and the order collapses to two tiers.
--
-- A SEPARATE TABLE, not a `TEXT[]` column on concepts, for three reasons:
--   · an alias carries its own provenance and admission time — B.4: *"AI may
--     propose a new concept or an alias; a human/curation step admits it"* —
--     and an array cannot carry per-element provenance;
--   · `normalised` must be UNIQUE across the whole taxonomy so that a duplicate
--     surface form is REJECTED at write time rather than discovered at read
--     time as an ambiguity; an array cannot be uniquely indexed across rows;
--   · the seeded tree is regenerated wholesale (see 014), and aliases must
--     survive that without being part of the generated artifact.
--
-- `normalised` is a STORED generated column so the database computes it, never
-- the caller. It mirrors `normaliseConceptText()` in `lib/concept-resolution.ts`
-- for the operations that are expressible in immutable SQL — lower, strip
-- apostrophes, `&` → " and ", collapse everything else to single spaces, trim.
-- Accent folding is deliberately NOT done here: `unaccent()` is not immutable
-- and cannot appear in a generated column without installing an extension, and
-- the application-side resolver folds accents before it queries. The column
-- exists to make DUPLICATES IMPOSSIBLE, not to be the resolver.
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS concept_aliases (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  concept_id  UUID NOT NULL REFERENCES concepts(id) ON DELETE RESTRICT,

  -- The surface form as a human would write it. Kept verbatim for display and
  -- for review; comparison uses `normalised`.
  alias       TEXT NOT NULL CHECK (length(btrim(alias)) > 0),

  normalised  TEXT GENERATED ALWAYS AS (
                btrim(
                  regexp_replace(
                    regexp_replace(
                      replace(
                        replace(replace(replace(lower(alias), '''', ''), '‘', ''), '’', ''),
                        '&', ' and '
                      ),
                      '[^a-z0-9]+', ' ', 'g'
                    ),
                    ' +', ' ', 'g'
                  )
                )
              ) STORED,

  -- Where it came from. `ai_proposed` exists so a proposal can be STORED
  -- without being trusted; the resolver reads admitted rows only.
  source      TEXT NOT NULL DEFAULT 'curated'
              CHECK (source IN ('seed', 'curated', 'ingestion', 'ai_proposed')),

  -- THE CURATION GATE (B.4). NULL means proposed but not admitted. An alias
  -- with no admission date never participates in resolution — the same shape
  -- as `ingestion_runs.confirmed_at` in 008: the column IS the record of when
  -- a human decided, and code that ignores it is visibly wrong.
  admitted_at TIMESTAMPTZ,
  admitted_by TEXT,

  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT concept_aliases_admission_shape CHECK (
    (admitted_at IS NULL AND admitted_by IS NULL)
    OR (admitted_at IS NOT NULL AND admitted_by IS NOT NULL)
  )
);

-- One surface form, one meaning. A second concept claiming the same normalised
-- alias is refused by the database rather than becoming a silent ambiguity in
-- every future resolution. Only ADMITTED aliases are constrained: two competing
-- proposals may coexist precisely because neither has been decided yet.
CREATE UNIQUE INDEX IF NOT EXISTS concept_aliases_normalised_unique
  ON concept_aliases (normalised) WHERE admitted_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS concept_aliases_concept_idx ON concept_aliases (concept_id);
CREATE INDEX IF NOT EXISTS concept_aliases_pending_idx
  ON concept_aliases (created_at DESC) WHERE admitted_at IS NULL;

-- An alias may not restate the concept's own name: that is the EXACT tier's
-- job, and duplicating it there would turn a tier-1 hit into a tier-1/tier-2
-- collision the resolver would have to arbitrate.
CREATE OR REPLACE FUNCTION concept_aliases_not_own_name() RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM concepts c
    WHERE c.id = NEW.concept_id
      AND btrim(regexp_replace(regexp_replace(
            replace(replace(replace(replace(lower(c.name), '''', ''), '‘', ''), '’', ''), '&', ' and '),
            '[^a-z0-9]+', ' ', 'g'), ' +', ' ', 'g')) = NEW.normalised
  ) THEN
    RAISE EXCEPTION 'alias % restates the concept''s own name; the exact tier already resolves it', NEW.alias;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS concept_aliases_not_own_name_trg ON concept_aliases;
CREATE TRIGGER concept_aliases_not_own_name_trg
  BEFORE INSERT OR UPDATE ON concept_aliases
  FOR EACH ROW EXECUTE FUNCTION concept_aliases_not_own_name();


-- ═══════════════════════════════════════════════════════════════════════════
-- 4 · ROW LEVEL SECURITY
--
-- Identical posture to `concepts` in 007 (`:319-324`), and for the identical
-- reason: *"The taxonomy is seeded and curated by the service role. A student
-- reads it and can never write it: it is the company's asset, not user data."*
-- An alias is taxonomy, so it inherits that exactly.
--
-- SELECT is restricted to ADMITTED aliases. A pending proposal is curation
-- state, not published vocabulary, and a client that could read it could also
-- resolve against it.
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE concept_aliases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS concept_aliases_select_admitted ON concept_aliases;
CREATE POLICY concept_aliases_select_admitted ON concept_aliases
  FOR SELECT TO authenticated USING (admitted_at IS NOT NULL);

-- No INSERT, UPDATE or DELETE policy. Under Postgres RLS that denies all three
-- to `authenticated` by construction — the same SELECT-only posture 012
-- established for `students` and `student_profiles`. The service role bypasses
-- RLS and is the only writer.


-- ═══════════════════════════════════════════════════════════════════════════
-- 5 · VERIFICATION — the file checks its own claims
--
-- Same discipline as 012 §7: a migration that asserts a posture should fail
-- loudly if the posture is not what it just built.
-- ═══════════════════════════════════════════════════════════════════════════
DO $$
DECLARE
  bad_policy TEXT;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'concepts' AND column_name = 'merged_into'
  ) THEN
    RAISE EXCEPTION '013 did not add concepts.merged_into';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'concepts' AND column_name = 'taxonomy_version'
  ) THEN
    RAISE EXCEPTION '013 did not add concepts.taxonomy_version';
  END IF;

  SELECT policyname INTO bad_policy
  FROM pg_policies
  WHERE tablename = 'concept_aliases' AND cmd <> 'SELECT'
  LIMIT 1;

  IF bad_policy IS NOT NULL THEN
    RAISE EXCEPTION 'concept_aliases has a non-SELECT policy (%): the taxonomy is service-role writable only', bad_policy;
  END IF;
END $$;


-- ═══════════════════════════════════════════════════════════════════════════
-- 6 · WHAT THIS MIGRATION DELIBERATELY DOES NOT DO
--
-- · It does not seed `concepts`. That is 014, kept separate because a schema
--   change and a data load fail differently and must be re-runnable apart.
-- · It does not add per-student state to `concepts`. B.4: *"Must NOT own
--   per-student state. Mastery. Difficulty for a given student."*
-- · It does not add an embedding column. B.4's third resolution tier is
--   embedding similarity; that is a model call, and every model call belongs to
--   the typed capability boundary (M15). Until then the third tier is lexical
--   and lives in `lib/concept-resolution.ts` — see that file's header.
-- · It does not add a merge-cycle trigger. Self-merge is refused above; a
--   longer loop needs a recursive check on every write, and the reader already
--   refuses a cycle rather than following it (`resolveMergeChain`). Revisit
--   when merges are performed by anything other than a curator.
-- ═══════════════════════════════════════════════════════════════════════════

-- >>> MIGRATION LEDGER REGISTRATION <<<
SELECT supabase_migrations.record_migration(
  '013',
  '013_concept_identity.sql',
  'bd36fb01bde03f25aef563c72ee00cc0924337d90113db912514c5de54831b21',
  'self'
);

-- What this part left behind, from the database rather than from a claim:
SELECT version, name, recorded_by FROM supabase_migrations.schema_migrations ORDER BY version;
